fix unpublished
2Abendsegler/GClh pull request #1422
Opened 2020-08-18 17:34 UTC by capoaira

- Remove functions for unpublished caches page (because GS removed the page)
- show unpublished hides again in the dashboard #1371

2020-08-18 17:37 UTC, capoaira commented
`getAsynData()` kann auch bei anderen Issues verwendet werden.

2020-08-25 19:04 UTC, Ruko2010 requested changes
Bei mir sieht das irgendwie komisch aus. ich habe nur einen Cache der Unpublished ist, eventuell liegt es da dran?
![image](https://user-images.githubusercontent.com/2239440/91216266-f2ad6200-e715-11ea-8dac-a375fef28f2c.png)

2020-08-25 20:53 UTC, capoaira commented
Scheinbar leitet GS einen von der Eventseite zur normalen Cacheseite, wenn man keine Events hat...

2020-08-26 13:54 UTC, capoaira commented
Ich habe mal einen fix eingebaut, kann aber nicht testen, ob er funktioniert.

2020-08-27 06:20 UTC, Ruko2010 requested changes
Bei mir wird nun  gar nichts mehr angezeigt :/ 

![image](https://user-images.githubusercontent.com/2239440/91399391-34392c80-e83e-11ea-874d-79752cc298f5.png)

2020-08-27 07:01 UTC, capoaira commented
Hast du lange genug gewartet, es kann schonmal ein paar Sekunden dauern...

2020-08-27 07:35 UTC, Ruko2010 commented
Auch nach ein paar Minuten passiert nix.

2020-08-27 08:05 UTC, capoaira commented
Ok, danke. Ich gucke mit das nach der Schule nochmal an. 
Hast du Fehler in der Konsole?

2020-08-27 08:26 UTC, Ruko2010 commented
Nein, nur die üblichen Warnings. Ich nutze Chrome als Dev-Browser, falls dir das weiter hilft.

Aber dazu auch noch ein kleiner Kommentar. Wenn die Ladezeit wirklich ein paar Sekunden beträgt, wäre es eventuell günstig das Feld schonmal anzeigen zu lassen und ein Lade-Gif zu zeigen, damit der User merkt, hier passiert noch was. Dann könnte man in meinem Fall auch sehen, ob das Feld/der Code überhaupt ausgeführt wird.
Wenn dann der Inhalt geladen ist, dann ersetzt du einfach das LadeGif durch den Inhalt.

2020-08-27 08:31 UTC, capoaira commented
Jip, das macht sinn. So werde ich das dann machen.

2020-08-27 18:02 UTC, capoaira commented
Jetzt sollte es funktionieren.
Folgende Änderungen:
- Loading spinner
- Bild wenn keine Caches gefunden wurden

2020-08-28 07:27 UTC, Ruko2010 commented
Da scheint der Hase im Pfeffer zu liegen:
![image](https://user-images.githubusercontent.com/2239440/91533705-a11cf700-e910-11ea-8487-03a46e6d085c.png)
![image](https://user-images.githubusercontent.com/2239440/91533717-a5491480-e910-11ea-9af4-9e0a1a67ffa8.png)
Darum hat er bei mir auch nix angezeigt. Da ist also noch irgendwas quer.

2020-08-28 12:39 UTC, capoaira commented
Hmmm, ich habe das eigentlich getestet...
Am WE bin ich nicht zu Hause. Habe zwar mein Surface dabei, aber ich glaube nicht, dass ich zum programmiren komme

2020-08-29 20:43 UTC, capoaira commented
Hmmm, bei mir klappt es, auch wenn ich nur einen Cache habe: 
![grafik](https://user-images.githubusercontent.com/50927164/91645807-f78d5100-ea48-11ea-9d3e-806db6f3c7e7.png)

2020-08-29 20:44 UTC, capoaira commented
Sind bei dir noch andere Scripte aktiv?

2020-08-31 07:46 UTC, Ruko2010 commented
Nein, nur mein GClh. Ich hab auch mal versucht den Code des Helpers direkt im Tampermonkey einzutragen, da ich dachte, dass es eventuell an der Einbindung als "Dev-Script" liegt, aber das führt zum gleichen Ergebnis. Es wird nichts angezeigt.

Ich hab mal ein bisschen Debugged, und wenn ich mal ein paar Logausgaben rein mache, dann sehe ich, dass der Handler der Funktion getAsynData bei mir gar nicht erst ausgeführt wird. Hier mein Testcode:
![image](https://user-images.githubusercontent.com/2239440/91695656-c7d86900-eb6e-11ea-896c-c910840cbc05.png)

2020-08-31 08:06 UTC, 2Abendsegler commented
Moin, ich hab die letzten Tage nichts gemacht, deshalb komme ich etwas verspätet mit meinem Punkt.

Ich kann das nicht wirklich beurteilen, aber ich meine wir haben jetzt eine ganz gute Seite für die Owner von Caches und Events, das Owner Dashboard. Außerdem peppen wir diese Seite ja auch noch weiter auf. 

Macht es wirklich Sinn im normalen Dashboard nochmal Informationen für die Owner abzulisten, die dann naturgemäß nicht so umfangreich und aussagekräftig sind wie im Owner Dashboard? In der Vergangenheit war das ja hilfreich, weil es eine vernünftige Seite für einen Owner ja nicht gab ... aber jetzt ... hmm?

2020-08-31 08:34 UTC, Ruko2010 commented
Ich brauch die Anzeige der Unpublished auch nicht, aber wenn es ein Problem in der getAsynData gibt, dann sollten wir das lösen, falls wir die Funktion öfter nutzen wollen.
@capoaira es war ja damals dein Wunsch die Unpublished dort anzuzeigen. Besteht der immer noch?

2020-08-31 13:42 UTC, capoaira commented
Das neue CO Dashboard ist tatsächlich gut und bietet eine gute Übersicht. Letztendlich spart diese Funktion nur ein klick, aber ich mag sie trotzdem. Wenn wir sie raus nehmen habe ich aber auch kein Problem damit.

@Ruko2010: Kannst du die Zeit nochmal etwas hoch setzten, evt. auf 10 sec? Wenn dass nicht klappt, versuche mal das iframe sichtbar zu machen und gucke was da geladen wird. Bei den BML habe ich dass Problem, dass ich immer die Mobile Seite bekomme, dann kann es sein, dass `.geocache-details` anders heißt.

2020-08-31 13:50 UTC, 2Abendsegler commented
> Bei den BML habe ich dass Problem, dass ich immer die Mobile Seite bekomme, dann kann es sein, dass `.geocache-details` anders heißt.

Der Grund für die Anzeige der Mobile Seite könnte das `width:100%` sein. Je nachdem wo du es einbaust, sind das nur ein paar Zeichen, deshalb wohl die Annahme dass die Mobile Seite angefragt wurde.

2020-09-01 05:20 UTC, capoaira commented
Der Übeltäter war das `display:none`, so hatte das iframe eine breite von 0.

2020-09-01 07:29 UTC, Ruko2010 commented
> @Ruko2010: Kannst du die Zeit nochmal etwas hoch setzten, evt. auf 10 sec? Wenn dass nicht klappt, versuche mal das iframe sichtbar zu machen und gucke was da geladen wird. Bei den BML habe ich dass Problem, dass ich immer die Mobile Seite bekomme, dann kann es sein, dass `.geocache-details` anders heißt.

Was genau meist du mit iFrame Sichtbar machen? zeit hochsetzen hat nix gebracht.

2020-09-01 07:47 UTC, capoaira commented
Das `display:none` und `visibility:hidden` ausblenden. Dann kannst du den Inhalt vom iframe sehen.

2020-09-01 13:29 UTC, capoaira commented
Ich habe nochmal etwas verändert, bei mir klappt es nach wie vor.
Kannst du nochmal testen ob es jetzt auch bei dir klappt?

2020-09-02 12:29 UTC, 2Abendsegler commented
@capoaira 
Wenn ich einen Cache anlege ohne ihn zum Reviewer zu schicken, kann ich dann hier auch mittesten, oder hilft das nichts?

2020-09-02 13:50 UTC, capoaira commented
Ja, dass geht. Der Cache muss nicht eingereicht werden.

2020-09-02 14:15 UTC, 2Abendsegler commented
Ich hab das jetzt auch auf die Schnelle ausprobiert mit FF und Chrome auf Win10. 

Hat bei zahlreichen Versuchen funktioniert. 

Nur einmal war ziemlich lange die Eieruhr da, unter Chrome, und dann ging sie irgendwann weg und es wurde kein Cache angezeigt. Vermutlich wurde die Zeit überschritten. Hier sollte dann besser so etwas angezeigt werden wie auch bei GS, so was wie "Probleme beim Laden" oder so, ich weiß jetzt nicht was die immer schreiben. 

Ansonsten sieht das auf die Schnelle schon in Ordnung aus. 👍

Die Frage ist nun aber nach wie vor, warum es bei Ruko2010 nicht angezeigt wird. Ich kann mir eigentlich nicht vorstellen dass das mit dem Mac zusammenhängt.

@Ruko2010 
Ich könnte mir das mit dem Config von dir ansehen. Du könntest deine Homekoordinaten ändern, deinen Config downloaden und mir per Mail schicken. Oder hier reinstellen, wenn es dich nicht stört dass jeder sehen kann welche Einstellungen du hast. Ich bevorzuge Mail.
Das ist nur ein Angebot falls du möchtest.

2020-09-07 13:04 UTC, Ruko2010 commented
Ich habe auch nochmal getestet. Bei mir klappt es nach wie vor nicht.
Nun habe ich seit ein paar Tagen ein Community Event bekommen und siehe da, das wird angezeigt. Mein anderer Hide aber nicht. Kann es eventuell daran liegen, dass der Cache schonmal beim Reviewer war, aber wegen eines Abstandkonflikts nicht gepublished wurde?? Hier mal noch ein paar Screenshots:

![image](https://user-images.githubusercontent.com/2239440/92390540-5c1c7000-f11b-11ea-9827-87021302d3c7.png)
![image](https://user-images.githubusercontent.com/2239440/92390551-60e12400-f11b-11ea-9c41-7cf8fe578735.png)
![image](https://user-images.githubusercontent.com/2239440/92390571-6ccce600-f11b-11ea-8bb1-8e588da84773.png)
![image](https://user-images.githubusercontent.com/2239440/92390576-71919a00-f11b-11ea-9372-dbc4032e8b6a.png)

2020-09-07 14:31 UTC, capoaira commented
Hmm, langsam gehen mir die Ideen aus.
Mit dem Status kann das nichts zu tun haben, da ich nur die Details abfrage. Ich überlege nochmal...

2020-09-08 05:45 UTC, Ruko2010 commented
Ich werde heute Abend auch nochmal Debuggen wenn ich die Zeit finde...

2020-09-08 20:11 UTC, Ruko2010 commented
So, hab das "Problem" gefunden. Und zwar hast du in deiner `getAsynData` zwei Werte drin, die die WaitTime bestimmen, `maxWaitCount` und `waitTime`.
Ich versteh nicht ganz, warum es da zwei Werte gibt? Vielleicht kannst du mir das kurz erklären.

Auf jeden Fall bricht bei mir das Laden an den 100 maxWaitCount ab. Ich hab das mal auf 1000 erhöht, da komme ich auf einen WaitCount von 300-600.

Wie gesagt, wenn ich den WaitCount auf 1000 setze klappt es dann mit beiden Caches. Ich weis nun nicht ob mein Rechner zu schnell ist, und sozusagen das Abrufen des Contents zu schnell geht und deswegen der Counter so schnell steigt, oder ob das Gegenteil der Fall ist und mein Rechner/Internet zu langsam ist 😃.

2020-09-08 21:40 UTC, capoaira commented
`maxWaitCount` gibt die an, wie oft abgefragt wird, `waitTime` gibt die gesamte Zeit in ms an. Wie lange zwischen den abfragen gewartet wird ergibt sich aus `waitTime/maxWaitCount`

Ich würde die default waitTime nochmal etwas erhöhen. 
Dann würde ich noch eine Kleinigkeiten ergänzen, sodass, wenn es keine unveröffentlichten Caches gibt, gar nicht erst abgefragt wird.

2020-09-09 05:52 UTC, Ruko2010 commented
Ok, das verstehe ich. Wenn ich die WaitTime auf 10 Sek. setze dann klappt es (obwohl es das beim letzten Versuch nicht hat 🧐🤔). Ich hab mal Logs ausgeführt, und ich komme bei ca. 80-90 waitcount raus. Also recht knapp. Setze ich sie auf 15 Sekunden, dann komme ich bei waitcount 60 ungefähr raus, also noch genug Luft nach oben. Auch wenn ich im Chrome den Sleep auf 3G ändere klappt es noch.

2020-09-09 14:15 UTC, capoaira commented
Ok, vielen Dank fürs testen. Ich die Wartezeit nun auf 15 sec hoch gesetzt. Damit sollte es dann klappen.

2020-09-10 06:00 UTC, Ruko2010 approved these changes
Es läuft nun, sehr gut. Kann gemergt werden.

2020-09-10 06:00 UTC, merged