Highlight found places from cache listing "Search in logtext" in the logs - Upload js
2Abendsegler/GClh pull request #1438
Opened 2020-09-01 13:14 UTC by 2Abendsegler

#1437

2020-09-01 14:35 UTC, 2Abendsegler commented
@Ruko2010 
Kannst du dir das bei Gelegenheit bitte mal ansehen, danke.

2020-09-07 13:06 UTC, Ruko2010 commented
Ich schau ob ich es Morgen Abend schaffe. Is grad etwas stressig bei mir.

2020-09-08 19:46 UTC, Ruko2010 requested changes
Läuft soweit. Eine kleine Änderung würde ich mir noch wünschen. Kannst du eventuelle Leerzeichen um das Trennzeichen "|" entfernen? Ich weis nicht ob ich es bin, aber ich mache zwischen den Wörtern und dem OR-Zeichen immer ein Leerzeichen.
![image](https://user-images.githubusercontent.com/2239440/92520851-8d309980-f21c-11ea-9cc8-fadc8a9fc8a9.png)
so ist es aktuell:
![image](https://user-images.githubusercontent.com/2239440/92520905-a5a0b400-f21c-11ea-81c5-ecbed3c0a065.png)

Ich hoffe es ist verständlich was gemeint ist.

2020-09-09 12:57 UTC, 2Abendsegler commented
Verstehe. Wie soll man dann aber eine Suche beispielsweise für " km", "km " oder "kilometer" eingeben. Hier arbeitet man ja mit Leerzeichen. Hier hatte ich übrigens gar nichts geändert, das war vorher auch schon so.
Ist das nur eine Angewohnheit von dir oder kommen bei dir die Leerzeichen automatisch.

2020-09-10 06:03 UTC, Ruko2010 commented
Ok, das macht sinn.
Die Leerzeichen kommen nicht automatisch, das ist eine Angewohnheit vom Programmieren 😃.
Dein Argument mit den km finde ich gut, also lassen wir es so.

2020-09-10 06:06 UTC, Ruko2010 approved these changes

2020-09-10 20:45 UTC, merged