View who favorited new
2Abendsegler/GClh pull request #1454
Opened 2020-09-11 08:44 UTC by 2Abendsegler

2020-12-14 06:40 UTC, 2Abendsegler commented
@Ruko2010, @capoaira:
Moin,

die Funktionalität zum Anzeigen der Favoriten in den Logs im Listing ist seit Version 0.10.7 so weit fertig. Im Listing gibt es oberhalb der Logs einen weiteren Button "Show who favorited" mit dem die Daten geladen und angezeigt werden. Beim Laden wird ein iFrame aufgebaut für die Seite "Users Who Favorited This Cache". Auf der Seite werden dann die einzelnen Seiten mit einem Klick auf "Next" geladen. Dadurch werden __doPostBack ausgelöst.

gcPhil hatte gelegentlich das Problem, dass scheinbar die Programmteile von GS, die den __doPostBack verarbeiten sollen, noch nicht vorhanden sind, so meine Interpretation. 

Vielleicht könnt ihr mal kurz testen ob sich bei euch ein solches Problem reproduzieren läßt, weil ich das Problem immer noch nicht reproduzieren kann und mir auch nichts mehr einfällt wie das Script mitbekommen soll, dass etwas schief gelaufen ist und es noch einmal auf den Button klicken soll.

Testen ist einfach:
- Spiele den PR auf, oder direkt [hier](https://github.com/2Abendsegler/GClh/blob/5516186595fa4e524730d1b7f4f52fe40596f21e/gc_little_helper_II.user.js?raw=true) 
- Gehe in ein Listing mit 100-400 Favoriten, oder nimm das [hier](https://coord.info/GC90EXB) 
- Klicke auf den Button "Show how favorited". Wird die Anzeige des Buttons nach 2 Minuten rötlich dann ist ein Fehler aufgetreten. Dann sehen wir weiter.

Bitte testet einige Male, weil es ja nicht immer passiert. Vielleicht auch mal zu unterschiedlichen Tageszeiten.

2020-12-14 20:04 UTC, capoaira reviewed
Erste Tests um 19:00 und 21:00 Uhr haben gut funktionert.
Ich gucke ob ich die Tage um andere Uhrzeiten nochmal teste. Hochzeit ist ja meist so ab 18 Uhr bei gute, Wetter am WE...

Edit: 11:00 Uhr sieht auch gut aus ;)

2020-12-28 18:45 UTC, Ruko2010 requested changes
Also bei mir klappt es gar nicht. Weder in meinem Listing, noch in dem, das du hier verlinkt hast. Ich habe in der Konsole immer den Fehler:
`Uncaught ReferenceError: __doPostBack is not defined at <anonymous>:1:1`

2020-12-28 19:02 UTC, 2Abendsegler commented
@Ruko2010 
Hey, schön von dir zu hören!

Wunderbar, dass es bei dir nicht funktioniert. Das ist der gleiche Fehler wie bei gcPhil im [Beitrag im Issue](https://github.com/2Abendsegler/GClh/issues/1054#issuecomment-687882219). 

Der Fehler hängt wohl damit zusammen, dass deine Leitung so schnell ist und die Gegenseite bei GS, die die Verarbeitung übernehmen soll, noch nicht fertig ist. 

Kannst du die Leitungsgeschwindigkeit mal drosseln und es dann nochmal versuchen. Oder stell mal die [Testparameter](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_who_favorited_but) ein. Vielleicht 500 millisekunden fürs Erste.
![grafik](https://user-images.githubusercontent.com/22332216/103237015-b51c4800-4946-11eb-9357-0ceedf3a11c3.png)

Meine Idee ist es nun, dass du versuchst herauszufinden, wie wir erkennen können, ob die Verarbeitung gegen die Wand gelaufen ist. Wenn wir das erkennen, dann können wir im Anschluss einfach nochmal auf den "Next" Button clicken und gut ist.

2020-12-28 19:25 UTC, Ruko2010 commented
Also am Speed liegt es nicht. Ich habe meinen Chrome mal auf "Slow 3G" geschalten, und der Fehler kommt trotzdem.
Dann habe ich die Verzögerung versucht. Bei 500 ms klappte es nicht. Bei 1500 schon. Dann habe ich es soweit reduziert, dass ich nun wieder bei 500ms bin und es immer noch klappt.
Zum Thema Fehler erkennen. Hast du den Buttonpress mal in einen Try Catch Block gepackt? Eventuell erkennt der den ja?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

2020-12-28 19:55 UTC, 2Abendsegler commented
Das sitzt alles in einem umfangreichen Try Catch Block. 

Der Fehler passiert aber nicht bei uns im Script, sondern bei der Folgeverarbeitung bei GS. Insofern kann ich mir auch gar nicht vorstellen, dass wir den Fehler in dieser Art bemerken könnten. 

Wir müssen auch nicht unbedingt den Fehler erkennen. Es würde auch reichen wenn wir erkennen, dass etwas am "Laufen" ist wenn wir den Button gedrückt haben bzw. wenn es eben nicht mehr am "Laufen" ist. Also wenn wir den Status des angetriggerten __doPostBack quasi verfolgen könnten.

2020-12-28 20:00 UTC, Ruko2010 commented
Schade, dann fällt mir leider auch nichts ein, wie man das umgehen könnte. Wie oft muss der Button denn gedrückt werden? Macht es eventuell Sinn, einfach immer 500-700ms zu warten, oder dauert es dann zu lange?

2020-12-28 20:15 UTC, 2Abendsegler commented
Ja, das warten und erneute Drücken des Buttons war quasi Stand der Dinge. Ich hatte das bereits versucht. Allerdings scheint es so, dass ein erneutes Drücken des Buttons das erste Drücken des Buttons vergessen macht, wenn ich zu schnell wieder drücke. Ich hatte es mit 500 ms versucht. 
Und eigentlich macht es auch gar keinen Sinn mehr, wenn das so lange dauert bis man weiter zur nächsten Seite blättern kann. Auf einer Seite sind 10 Einträge. Hat ein Cache beispielsweise 100 Favoriten, dann muss man 9 mal blättern. Bei 1000 muss man 99 mal blättern.
Wenn das bei dir so lange dauert dann müsstest du auch beim manuellen blättern in der Favoritenliste des Caches schon auf einen Fehler laufen.

2020-12-28 20:49 UTC, Ruko2010 commented
Macht dieses Feature dann überhaupt Sinn 😃?

2020-12-28 21:17 UTC, 2Abendsegler commented
Ja, die Frage muss man sich schon stellen.

Wenn du wissen möchtest, ob jemand einen Favoritenpunkt vergeben hat, dann gibt es mit den Mitteln von GS nur die Möglichkeit unter "View Who Favorited" nachzusehen. Da die entsprechende Liste nicht sortiert ist, musst du die Liste quasi komplett durchblättern. Das ist genau das was wir mit diesem Feature auch machen, nur eben per Programm.

Es scheint Cacher zu geben die das bei jedem neuen Log machen, so Beiträge im GS Forum.

Für 100 Favoriten braucht es bei mir etwa mehr als 10 Sekunden. Das liesse sich noch tunen um schätzungsweise 30% wenn man gleichzeitig auch von hinten aus anfängt zu blättern.

Ich fand es ok die 10 Sekunden zu warten für diese Info. 

Natürlich wäre es schöner wenn es noch schneller gehen würde. Und bei 1000 Favoriten macht es mir dann auch keinen Spaß mehr.

2020-12-29 06:28 UTC, Ruko2010 commented
Dann sollte man eventuell über den Button einen Infotext machen (Also einer der aufploppt, wenn man drüber hovered). Sowas wie: "Achtung, Aufgrund der Beschränkungen von Groundspeak dauert der Abruf pro 10 Favoritenpunkten ca. 1 Sekunde."

2021-04-25 13:26 UTC, 2Abendsegler commented
Closed
Siehe #1054.

2021-04-25 13:26 UTC, closed without merging