fix Hide found/own caches, cache types
2Abendsegler/GClh pull request #1495
Opened 2020-11-12 14:46 UTC by capoaira

#1478

2020-11-24 11:39 UTC, 2Abendsegler requested changes
Fehler:
"Found status: Not found" wird nicht gesetzt. "Cache owner: Caches I don’t own" wird gesetzt.

- Wenn ich die Verarbeitung für "Cache owner: Caches I don’t own" im Script zuerst ausführen lasse, dann wird dieses Flag nicht gesetzt und "Found status: Not found" wird gesetzt.
- Wenn ich als Wartezeit 1000 anstatt 50 Millisekunden eingebe funktioniert alles. So sollten wir es natürlich nicht machen.
- Zu warten bis "#search-filter-type" vorhanden ist scheint also nicht ausreichend, die Found status Radio Buttons sind dann noch nicht unbedingt da. Ich weiß nicht wie man auf die Radio Buttons abfragen kann.

Kann das was mit den ursprünglichen Doppelclicks zu tun haben?

2020-11-24 12:40 UTC, capoaira commented
Die Ursprünglichen Doppelklicks haben nicht mehr funktioniert (keine Ahnung warum)
Scheibar ist die ach so tolle, neue, schnellere Karte langsamer...🤣

Den Fehler gucke ich mir gleich mal an...

2020-11-24 14:09 UTC, capoaira commented
Der Doppelklick hat doch seinen Sinn. Zudem muss man noch auf den einen radio warten.

Weitere Änderung: Wenn man alle Cachetypen ausblendet konnte der Filter nicht abgeschickt werden.

2020-11-24 14:59 UTC, 2Abendsegler requested changes
1. Egal welche Cachetypen ich auswähle, sie werden nie gesetzt.
ich habe 
`return count = 9;`
durch
`if (cache_types.length == count) return true;`
ersetzt.
Das scheint dann zu funktionieren. Habs aber nicht ausführlich getestet weil ich immer wieder über 2. gestolpert bin.
 
2. Wenn ich alle Cachetypen auswähle, dann sollten hide found und hide own trotzdem gesetzt werden. Ist gefühlt die halbe Zeit so. Die andere halbe Zeit werden sie aber nicht gesetzt.
Ich kann nichts erkennen warum das so ist.

---
Ich halte mich immer an den Grundsatz "Do not change a running system, es sei denn es ist absolut notwendig". Deshalb bin ich auch immer gegen refactoring. Insofern würde ich wieder alles zurückbauen, was vorher mal funktioniert haben sollte, und ich würde nur diejenigen von deinen Änderungen belassen, von denen ich genau weiß dass sie geändert werden müssen.

Beispielsweise würde ich auch den Doppelclick bei 
`//apply filters to map and close`
wieder einbauen. (Das hatte ich schon gemacht, dadurch hatte sich aber nichts verändert. Diente auch nur als Beispiel.)

2020-11-24 15:16 UTC, 2Abendsegler commented
Ich habe noch etwas rumgespielt. Es scheint so, dass 2. nur dann auftritt wenn Hide sidebar gesetzt ist. Vielleicht macht das Einklappen der Sidebar Änderungen unmöglich?

2020-11-24 16:59 UTC, capoaira commented
`return count = 9;` Ich Idiot, das müsste natürlich `return count == 9;`
Aber auch das bringt im Moment nichts. Ich habe gerade mal weiter getestet und jetzt funktionert bei mir nicht mal mehr die erste Version...
Wenn ich die Änderungen allerdings zusammen mit den anderen ausprobiere, klappt es...
Hier müssen wir also scheinbar auch auf #1499 warten.
Wenn du mal alle Änderungen zusammen ausprobieren möchtest, kannst du das [hier ((https://github.com/capoaira/GClh/blob/New-Map/all/gc_little_helper_II.user.js?raw=true)](https://github.com/capoaira/GClh/blob/New-Map/all/gc_little_helper_II.user.js?raw=true) tun.

2020-11-24 18:42 UTC, 2Abendsegler commented
Das geht jetzt etwas zu viel durcheinander. :)

Die jetzige Version macht nicht so viel Sinn:
- [ ] Weil nur auf '#search-filter-type' gewartet wird und nicht auch auf die Radio Buttons. 
- [ ] Und weil die Prüfung ob alle Cachetypen deaktiviert sind wieder rein muss.
- [ ] Und weil Hide sidebar eine Änderung der Filter verhindert, die sidebar muss also hinten angestellt werden.

Ich schlage aber auch vor dass wir zuerst auf #1499 warten und dann die Sache nochmal angehen.

2020-11-24 19:13 UTC, capoaira commented
Die Version nach dem 2. Commit hat mehr Probleme gemacht, als die Erste. Deswegen habe ich den commit rückgänig gemacht um auf #1499 zu warten ;)

2020-11-26 17:43 UTC, capoaira commented
So auch hier ein rebase und ein commit damit alles wieder läuft

2020-11-26 21:03 UTC, 2Abendsegler reviewed
Sieht ziemlich gut aus!

Hab nur ein kleines Problem. Manchmal werden gar keine Parameter übernommen. Die Parameter sind zwar gesetzt, der Filter wurde aber nicht aktiviert. Scheinbar stimmt das auch hier, dass es nur mit doubleclick verlässlich läuft. 

Ersetze bitte
`$('button.control-apply').click();`
wieder durch
`doubleClick('button.control-apply');`

Ich habs ne ganze Weile ausprobiert, mit dem doubleclick scheint es zu funktionieren.

2020-11-26 22:08 UTC, capoaira commented
Habe es angepasst

2020-11-27 00:56 UTC, 2Abendsegler approved these changes
Super, danke, richtig gut! :)

2020-11-27 00:57 UTC, merged