rewrite MutationObserver on searchmap
2Abendsegler/GClh pull request #1499
Opened 2020-11-22 12:06 UTC by capoaira

#1478
Nachdem ich gesehen habe, dass GCTour nach funktioniert habe ich mir den Code angeschaut und etwas verändert übernommen. So funktionieren die Cachedetails wieder. 
Das heißt:
- Ownerangabe wird bei Compact Layout wieder angezeigt 
- Cachename wird verlinkt und bei disabled durchgestrichen
- Show hint of cache automatically funktioniert wieder
- scroll to last position funktioniert wieder, aber nicht perfekt
- #1489 ist damit auch gefixed (Sorry @Ruko2010, ich wollte dir nichts wegnehmen)

Das Compact Layout in der Liste funktioniert noch nicht. Ich denke da wurde einiges umbenannt....

2020-11-23 08:04 UTC, Ruko2010 commented
> * #1489 ist damit auch gefixed (Sorry @Ruko2010, ich wollte dir nichts wegnehmen)

Jetzt bin ich aber sauer, dass du mir die Arbeit abgenommen hast 😅
Nein Spaß, schön wenn alles wieder klappt. ich schau es mir heute Abend an.

2020-11-23 22:01 UTC, Ruko2010 approved these changes
Sieht für mich gut aus.

2020-11-24 10:31 UTC, 2Abendsegler requested changes
Sieht alles wieder einigermaßen aus. Bei GC Tour zu schauen war ne gute Idee.

Bei zugeschaltetem GC Tour gibt es allerdings nun zweimal den Auto Tour Button oben im Header. Kannst du da nochmal schauen. (Ich verstehe die Änderungen nicht wirklich, sonst würde ich es ja selbst machen.)

2020-11-24 12:36 UTC, capoaira commented
Den doppelten AutoTour Butten habe ich schon seit langem immer mal wieder. Das hat nichts mehr meinen Änderungen zu tun.

Letztendlich passiert genau das selbe, wie vorher, nur das die anonyme Funktion nun benannt ist (finde ich übersichtlicher bei 2 Observern). 
Zudem gibt es nun einen 2. Observer, der sich nur auf Sidebar konzentriert und das Attribut `subtree: true` hat. Damit sich der Observer nicht aufhängt wird er am Anfang des callbacks disconnected und am Ende nimmt er seine Funktion wieder auf.

2020-11-24 12:40 UTC, 2Abendsegler commented
Hmm ... aber wenn ich deine Änderungen weglasse, ist bei mir auch der doppelte GC Tour Button nicht mehr da. Ich hab den auch noch nie gesehen.

2020-11-24 13:19 UTC, capoaira commented
Bei mir ist es auch nur manchmal, aber egal welche gclh version ich installiert habe. Allerdings ist er mir jetzt beim testen zumindestens nicht untergekommen, wenn ich den GClh ganz abgeschaltet habe. Es liegt also wahrscheinlich am ersetzen des Headers. Vielleicht können uns @DieBatzen weiterhelfen?

2020-11-24 13:30 UTC, 2Abendsegler commented
> Es liegt also wahrscheinlich am ersetzen des Headers.

Das könnte sein.

@DieBatzen
Moin Thomas, 
das von @capoaira beschriebene Phänomen sieht dann etwa so aus. Der große Button ist super schnell da, der kleinere kommt etwas später. 
![grafik](https://user-images.githubusercontent.com/22332216/100100230-c3b3a300-2e60-11eb-87c0-bdfdf83a398b.png)
Fällt dir dazu was ein?
LG Frank

2020-11-24 18:32 UTC, DieBatzen commented
Ja wo kommt den dieser komische zweite Button her? ;)
Sieht interessant aus ...

Im Ernst, habe ich so auch noch nie gesehen.
Ich habe mir eben den PR + die GCTour Releaseversion unter Chrome und FF geladen und sehe ... jeweils nur einen Button.

Auch das Ändern der Skriptreihenfolge im TM ändert daran nichts.
Vielleicht ändert das ja bei euch etwas?

Der "richtige" (kleinere) AutoTour-Button kommt deswegen leicht zeitverzögert, weil er sich vor das Messagecenter-Icon setzt und solange wartet, bis der Header fertig ausgetauscht ist (bzw. nach 1s Wartezeit).
Er wird aber definitiv nur einmal hinzugefügt, von daher müsste der zweite eine Kopie des ersten sein.
Dass der große Button allerdings sofort da ist, klingt seltsam. Da habe ich leider keine Idee, wo der herkommen könnte.

Am plausibelsten scheint mir auch der Headertausch als Ursache.

2020-11-24 19:05 UTC, 2Abendsegler commented
@DieBatzen
Danke für die Rückmeldung!

Ich vermute dass die Wartezeit von 1s gelegentlich nicht ausreicht, GC Tour den Button erzeugt und wir ihn dann womöglich mit dem Header kopieren. Bei der neuen Karte müssen wir uns den Header zuerst von einer anderen Seite laden, um ihn dann angepasst in der neuen Karte zu setzen. Das dauert etwas länger als bei anderen Seiten. Der erste Button könnte also womöglich doch von GC Tour sein.

capoaira kennt den fetten Button ja schon länger. Und ich würde mal vermuten dass er ihn auch nur von der neuen Karte kennt. Er kommt ab und zu mal. Das ist also ein Problem das schon länger besteht und sehr wahrscheinlich nicht mit unseren aktuellen Änderungen zu tun hat. Wenn ich die aktuellen Änderungen von capoaira verwende kann ich aber den fetten Button häufiger erzeugen. Ich habe eine etwas schwache Leitung, was der Grund dafür sein könnte. Ich könnte in einfacher Art und Weise prüfen, ob die 1s zu wenig ist. Hast du die Stelle in GC Tour vielleicht parat?

Danke dir.

2020-11-24 19:08 UTC, DieBatzen commented
Klar, Zeile 3509.

2020-11-24 19:16 UTC, capoaira commented
> Und ich würde mal vermuten dass er ihn auch nur von der neuen Karte kennt. 

Tatsächlich. Ich habe nie drüber nachgedacht, aber stimmt, ich kenne den Button nur von der searchmap.

2020-11-24 20:42 UTC, 2Abendsegler commented
@DieBatzen 
GC Tour erzeugt doch beide Buttons auf der neuen Karte. 
- Einmal im Rahmen der Verarbeitung der alten Karte ab Zeile 3363 (hatte bei Zeile 3386 title in "OLD map to autoTour" geändert) 
- und einmal im Rahmen der Verarbeitung der neuen Karte ab Zeile 3459 (hatte bei Zeile 3481 title in "NEW map to autoTour" geändert und bei Zeile 3509 500 Millisekunden angegeben).

Ich hätte eigentlich erwartet dass die beiden Buttons immer kommen müssten, ist ja aber nicht so. Das habe ich nicht verstanden, macht aber nix, du wirst das sicherlich verstehen.

Änderung in Zeile 3364 
```
alt  	if (document.URL.search("\/map\/") >= 0) {
neu 	if (document.URL.search("\/map\/") >= 0 && !document.URL.search("\/play\/map")) {
```
behebt den Effekt bei mir.

![grafik](https://user-images.githubusercontent.com/22332216/100148910-b10b8f00-2e9d-11eb-9c75-836ed398a9e2.png)

2020-11-24 21:44 UTC, DieBatzen commented
Ui, guter Fang!

`document.URL.search("\/map\/")` sucht nach dem Muster `/map/`, damit Adressen der Art `https://www.geocaching.com/map/#?ll=50,8&z=14` --> Browsemap

Die Adressen der Searchmap hingegen sind normalerweise so aufgebaut:
`https://www.geocaching.com/play/map?lat=50&lng=8&zoom=14&asc=true&sort=distance`, also mit Muster `/map`.

Und genau das ist der Knackpunkt:
`https://www.geocaching.com/play/map/?lat=50&lng=8&zoom=14&asc=true&sort=distance` ist ebenfalls eine gültige Adresse der Searchmap, also mit Muster `/map/`.
Damit kann ich den "großen" Button auch direkt sehen ...

Ich vermute, die Searchmap-Links werden an verschiedenen Stellen unterschiedlich aufgebaut, einmal so `/map*` und einmal so `/map/*`.
Das erklärt, warum der große Button manchmal zu sehen war und manchmal nicht.

Auf jeden Fall löst dein Fix das Problem, werde ich in der nächsten GCTour-Version einbauen.

Herzlichen Dank fürs Debuggen!

2020-11-26 14:37 UTC, 2Abendsegler commented
Bau mal bitte noch die angemerkte Zeile aus. Dann kann ich das mergen und mit den zahlreichen anderen Dingen beginnen, die darauf aufbauen. :)

2020-11-26 15:02 UTC, capoaira commented
Ich stehe gerade etwas auf dem schlauch, welche Zeile meinst du?

2020-11-26 15:30 UTC, 2Abendsegler commented
Du hattest eine Zeile ersetzt.
Alt: 
`css += '.search-filters-block ul label {padding: 3px 10px !important;}';`
Neu: 
`css += '.search-filter-type ul label {padding: 3px 10px !important;}';`

Schau gegebenenfalls im Reiter "Files changed" und geh ganz nach unten.

2020-11-26 15:39 UTC, capoaira commented
Ah ok. Habe die Änderung entfernt

2020-11-26 15:46 UTC, 2Abendsegler approved these changes
Ok, danke.

2020-11-26 15:47 UTC, merged