Remove code and upload js
2Abendsegler/GClh pull request #1515
Opened 2020-11-24 22:26 UTC by 2Abendsegler

[Old bookmarklists] Remove old bookmarklists functionality. #1514

2020-11-25 15:42 UTC, capoaira approved these changes
Sieht alles gut aus

2020-11-25 16:11 UTC, capoaira requested changes
Old Bookmark auch in VIP/VUP entfernen: Z. 5968 und 6528

2020-11-25 18:17 UTC, 2Abendsegler commented
> Old Bookmark auch in VIP/VUP entfernen: Z. 5968 und 6528

Hast recht, das kann auch raus. Erledigt.
(Eigentlich geht es hier aber nicht darum alles zu erwischen, sondern nur darum große Blöcke an Coding rauszufeuern. Tatsächlich nutzen wir ja noch was aus der alten Bookmarklisten Verarbeitiung (Cache Listing "Add to list" mit rechter Maustaste).)

2020-11-25 18:19 UTC, capoaira commented
> (Eigentlich geht es hier aber nicht darum alles zu erwischen, sondern nur darum große Blöcke an Coding rauszufeuern. Tatsächlich nutzen wir ja noch was aus der alten Bookmarklisten Verarbeitiung (Cache Listing "Add to list" mit rechter Maustaste).)

Ok, mir ist das nur aufgefallen, weil ich mein Owner Dashboard drüber gestolpert bin ;)

2020-11-25 18:20 UTC, capoaira approved these changes

2020-11-26 14:38 UTC, capoaira requested changes
Igendwie fallen mir die Sachen nur Stück für Stück auf...

Mir ist gerade aufgefallen, dass es in den Settings noch die Überschrift "Old bookmark lists only" gibt.
![grafik](https://user-images.githubusercontent.com/50927164/100363381-ef6b9000-2ffc-11eb-81bd-62a8359e9e39.png)
Das sollte auf jeden Fall noch entfernt oder in die neuen BML übernommen werden...

2020-11-26 15:10 UTC, 2Abendsegler commented
Ja, hast eigentlich recht ... aber
- Der erste Parameter und die Funktionalität dahinter wird auch in der Watchlist verwendet. 
- Der zweite und dritte Parameter wird noch verwendet wenn man aus dem Cache Listing heraus über "Add to list" per rechter Maustaste und Tab öffnen in die alte Verarbeitung springt um eine neue Bookmark mit Beschreibung zu speichern.

In der neuen BML gibt es diese Funktionalität nicht, wir können es also auch nicht dort hin übernehmen. Es ist einfach so, dass es die alten BML noch gibt.

Lediglich der vierte Parameter kann vermutlich entfernt werden, dazu müsste ich aber tiefer einsteigen um sicherzustellen, dass ich nichts kaputt mache. Genau das wollte ich aber nicht. Wir müssen nicht alles erwischen. Es geht hauptsächlich um eine Reduktion des Codes, aber ohne viel Aufwand zu treiben und Gefahr zu laufen, dass etwas kaputt geht.

2020-11-26 15:20 UTC, capoaira approved these changes
Ich habe die alten BML nicht mehr gesehen, seit dem es die neuen gibt. Wie kommt man auf die alten?
Ich dachte die Alten gibt es nicht mehr, deswegen hätte ich das in den Settings verwirrend gefunden. Es ging mir nicht um den Code zu erwischen, sondern um die Übersichtlichkeit in den Settings.

Wenn die Funktionen natürlich noch genutzt werden, macht es keinen Sinn sie zu entfernen...

2020-11-26 15:41 UTC, 2Abendsegler commented
> Wie kommt man auf die alten?

Geh mal in ein Cache Listing. 
Fahre mit der Maus über "Add to list", klicke rechte Maustaste und wähle "Link in neuem Tab öffnen".
![grafik](https://user-images.githubusercontent.com/22332216/100369608-64db5e80-3005-11eb-9601-40f80c9d207d.png)
Der Button unten kann mit F2 betätigt werden. Wenn du das machst wird eine Bookmark erzeugt und du wirst automatisch in die BML weitergeleitet, sofern du das eingestellt hast.

Ok?
 
> Ich dachte die Alten gibt es nicht mehr, deswegen hätte ich das in den Settings verwirrend gefunden. Es ging mir nicht um den Code zu erwischen, sondern um die Übersichtlichkeit in den Settings.

So wie dir wird es auch anderen gehen. 
Vielleicht sollte ich mir doch noch Gedanken machen wie man das anders machen kann.

2020-11-26 16:33 UTC, capoaira commented
Ah ok, das wusste ich nicht 👍🏻

2020-11-27 03:03 UTC, 2Abendsegler commented
Ich hab das im Config noch überarbeitet und den ganzen Block mit alten BML aufgelöst, so wie du vorgeschlagen hast. 
Schaus dir bitte noch mal an.

---
Die Steuerung der Anzahl der Caches in der Watchlist ist bei "Others" im Config. Das war schon so, das ist nicht neu.
![grafik](https://user-images.githubusercontent.com/22332216/100403874-4a829e80-3060-11eb-87cc-484371fcb23e.png)
Änderungen bei den BML:
![grafik](https://user-images.githubusercontent.com/22332216/100404923-d3023e80-3062-11eb-95a0-ef982baf2ea6.png)
Die Hilfetexte wurden auch angepasst.

2020-11-27 14:47 UTC, capoaira approved these changes
Sieht gut aus 👍

2020-11-27 15:02 UTC, 2Abendsegler commented
@capoaira Danke!
@Ruko2010 Magst du auch noch drüber schauen, ob dir etwas einfällt was dagegen spricht das Coding zu entfernen?

2020-11-27 21:29 UTC, Ruko2010 approved these changes
Sieht auch für mich gut aus!

2020-11-27 22:13 UTC, merged