How you can install gclh on android devices
2Abendsegler/GClh pull request #1521
Opened 2020-11-25 12:55 UTC by 2Abendsegler

#1519

2020-11-25 13:25 UTC, 2Abendsegler commented
@Ruko2010, @capoaira:
Könnt ihr euch bitte die beiden Dokumente in beiden Sprachen ansehen ob sie ok und verständlich sind. Nur die direkt angesprungenen Abschnitte sind relevant.
[tips_installation.md en](https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/tips_installation.md#android_en)
[tips_installation.md de](https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/tips_installation.md#android_de)
[faq.md 4. en](https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/faq.md#4-en)
[faq.md 6. en](https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/faq.md#6-en)
[faq.md 4. de](https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/faq.md#4-de)
[faq.md 6. de](https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/faq.md#6-de)

2020-11-25 16:28 UTC, capoaira reviewed
Sieht für mich gut aus. Ich habe nur zwei Kleinigkeiten gefunden:

2020-11-25 16:28 UTC, capoaira commented on docu/faq.md
> +		Bei kleineren Android Geräten, wie zum Beispiel Smartphones, werden einige Geocaching Seiten in einem kleineren (Mobil) Layout dargestellt. Der GClh unterstützt solche Layouts nicht. Das kann dazu
Komma zwischen `führen` und `dass`
Das kann dazu führen, dass die Geocaching Seite nicht ordnungsgemäß angezeigt wird.

2020-11-25 16:28 UTC, capoaira commented on docu/tips_installation.md
> +* Wir supporten Android Geräte zur Zeit nicht. Dennoch ist das Script auch unter Android funktionsfähig mit nur wenigen Einschränkungen. <a href="/docu/faq.md#4-de" title="Link to 'FAQ 4. Hints for u
Title ist English statt Deutsch

2020-11-25 18:24 UTC, 2Abendsegler commented on docu/faq.md
> +		Bei kleineren Android Geräten, wie zum Beispiel Smartphones, werden einige Geocaching Seiten in einem kleineren (Mobil) Layout dargestellt. Der GClh unterstützt solche Layouts nicht. Das kann dazu
erledigt, danke

2020-11-25 18:24 UTC, 2Abendsegler commented on docu/tips_installation.md
> +* Wir supporten Android Geräte zur Zeit nicht. Dennoch ist das Script auch unter Android funktionsfähig mit nur wenigen Einschränkungen. <a href="/docu/faq.md#4-de" title="Link to 'FAQ 4. Hints for u
erledigt, danke

2020-11-25 19:37 UTC, Ruko2010 commented
https://github.com/2Abendsegler/GClh/blob/How-you-can-install-GClh-on-Android-devices/docu/tips_installation.md#android_de
=> Wir supporten Android Geräte zur Zeit nicht. Dennoch ist das Script auch unter Android funktionsfähig mit nur wenigen Einschränkungen.
Ich würde hier schreiben:
=> Wir unterstützen zur Zeit keine Android Geräte. Dennoch ist das Script mit nur wenigen Einschränkungen auch unter Android funktionsfähig.

Ansonsten sieht es gut aus.

2020-11-25 19:38 UTC, Ruko2010 requested changes
Siehe mein letzter Kommentar

2020-11-25 19:43 UTC, 2Abendsegler commented
@Ruko2010 
Hab das noch geändert. Danke.

2020-11-26 13:54 UTC, capoaira approved these changes
Für mich sieht das gut aus.

2020-11-27 01:52 UTC, merged