Issue/1498 how to contribute
2Abendsegler/GClh pull request #1529
Opened 2020-11-27 21:01 UTC by Ruko2010

2020-11-27 21:06 UTC, Ruko2010 commented
@2Abendsegler @capoaira 
Könnt ihr beide bitte auch nochmal über die Englische Version lesen? Ich bin da ja nicht die Top Wahl als Übersetzer, aber ich hab mein bestes gegeben. Bin aber für Verbesserungen offen 😃.

2020-11-27 22:09 UTC, 2Abendsegler commented
Eigentlich ist das total doof dass ich nicht direkt im Dokument ändern kann, das würde genauso schnell gehen. Und du musst das jetzt alles nochmal machen.

---
Alle Links in den Dokumenten könnte man wie folgt darstellen damit immer die jeweils passende Datei, und nicht aus dem Master, gezogen wird.
"../README.md" glaube ich
"../doku/faq.md" glaube ich
...

---
README.md
- "improvements" anstatt "improvments"
- "how to contribute" anstatt "How to contribute". Hier geht es ja nicht um den Dokumentennamen, sondern um den hier zu lesenden Text und der wird klein geschrieben.
- beitragen anstatt betraben :)

---
faq.md
- "7. Wie kann ich etwas zu GClh II beitragen" anstatt "6. Wie kann ich etwas zu GClh II beitragen"
- "features" anstatt "Features"
- "pull requests" (so schreibt es github auch) anstatt "Pull-Requests" (mehrfach)
- "Pull Requests" (im deutschen) anstatt "Pull-Requests"

---
how_to_contribute.md
- Englisch kommt eigentlich immer als erstes.

deutsch
- "oben rechts" anstatt "oben Rechts"
- Der lange Bindestrich bei "GC little helper II — Entwicklung mit Tampermonkey" ist unschön. Sollte auch im Original Dokument geändert werden.
- "Reiter Pull requests (1.)" anstatt "Reiter Pull Requests (1.)"

englisch
- "pull request" anstatt "Pull Request" (mehrfach, du kannst aber nicht alle auf einmal ersetzen weil es auf den Screens ja auch Pull reuest heißt.)
- "Github account" anstatt "Github Account" (mehrfach) (Github ist Eigenname, Account nicht)
- "repository" anstatt "Repository" (mehrfach)
- "Git client" anstatt "Git Client"
- "webinterface" anstatt "Webinterface"
- "feature / change" anstatt "changes/feature" (so hast du es an anderer stelle geschrieben)
- "tab pull requests (1.)" anstatt "tab Pull Requests (1.)"
- "otherwise you can't create a Pull Request with changes in OUR? Repository." anstatt "otherwise you can't create a Pull Request with changes in your Repository."

---
development-tampermonkey.md (ich weiß das war schon da)
- Sprachen oben zum Anwählen fehlen
- Englisch kommt eigentlich immer als erstes.
- Der lange Bindestrich bei "GC little helper II — Entwicklung mit Tampermonkey" ist unschön. Im englischen genauso.
- Am ende einer Sprache einen fetten Strich ---

2020-11-27 22:10 UTC, 2Abendsegler requested changes
Siehe oben

2020-11-27 23:28 UTC, Ruko2010 commented
> Eigentlich ist das total doof dass ich nicht direkt im Dokument ändern kann, das würde genauso schnell gehen. Und du musst das jetzt alles nochmal machen.

Das hab ich mir auch schon gedacht. Aber müsste es nicht klappen, wenn du hier im PR einfach auf *Files Changed* klickst, dann die entsprechende Datei suchst und dann auf die drei Punkte klickst und dann auf *Edit File*. Oder geht das nur bei mir, weil es mein PR ist?
![image](https://user-images.githubusercontent.com/2239440/100488785-8bd28700-3110-11eb-8dac-964fa61f1989.png)

![image](https://user-images.githubusercontent.com/2239440/100488758-6e9db880-3110-11eb-926b-2000c13b56b4.png)

2020-11-27 23:28 UTC, Ruko2010 commented
Ich werde deine Anmerkungen aber noch umsetzen (denn jetzt hast du dir ja die Arbeit schon gemacht und sollst das nicht nochmal tun). Aber nicht mehr heute 😃.

2020-11-27 23:34 UTC, 2Abendsegler commented
Das geht ja wirklich, ich hatte das gar nicht versucht ... sehr schön. :)

2020-11-27 23:37 UTC, Ruko2010 commented
Macht ja auch Sinn dass das geht, denn der PR gehört ja zu deinem Repo, also musst du auch Änderungen machen können.
Außerdem ist es ja nur Sinnvoll, dass du noch was ändern kannst bevor du es mergest, da der "fremde" Code ja in deinen eigenen übergeht und du eventuell nicht alles so haben willst, wie der Contributer es "vorgeschlagen" hat.

Aber gut, dass wir das geklärt haben. Wieder was gelernt 😃.

2020-11-27 23:40 UTC, 2Abendsegler commented
Ich kann es halt im Script nicht ändern weil die Datei zu groß ist und irgendwie hat sich das festgesetzt dass das nicht geht.

> Aber gut, dass wir das geklärt haben. Wieder was gelernt 😃.

Ja genau.

2020-11-30 17:28 UTC, 2Abendsegler commented
@Ruko2010 
Ich mach die Änderungen ... leg die Füße hoch ... 😄
Vielleicht kann ich dann heute noch ne neue Version rausschicken, sofern ich das Problem mit dem gelegentlich fehlenden Mutation Observer bei der neuen Karte noch geregelt bekomme.

2020-11-30 17:33 UTC, capoaira commented
> Problem mit dem gelegentlich fehlenden Mutation Observer bei der neuen Karte noch geregelt bekomme.

Wann fehlt der MutationObserver bei dir? Ich hatte bis jetzt noch keine Probleme.
Ich denke, dass man dann wieder auf den Body warten muss. Den Part hatte ich bei #1499 entfernt.

2020-11-30 17:39 UTC, 2Abendsegler commented
> Wann fehlt der MutationObserver bei dir? Ich hatte bis jetzt noch keine Probleme.
> Ich denke, dass man dann wieder auf den Body warten muss. Den Part hatte ich bei #1499 entfernt.

Ganz zu Begin wenn die neue Karte aufgerufen wird, dann werden die css in der Cacheliste ausgeführt, klar, aber die Dinge die über die Mutation Observer kommen sollen fehlen. Also beispielsweise in der Cache Liste mach aus 3 Zeilen 2 Zeilen. Wackele ich an der Karte, dann wird das alles nachgeholt.
Vermutlich kommt das daher, dass ich keine gute Leitung habe. Gestern, an einer besseren Leitung, hatte ich das Problem nicht. 
Wenn ich es nicht anders geregelt bekomme, dann baue ich das Warten auf body wieder ein, guter Punkt.

2020-11-30 17:46 UTC, capoaira commented
Dann wird dass warten nichts bringen, weil der Mutation Observer ja gesetz wird. Zumindest der für den body. Dein beschriebenes Problem klingt nach einem Problem mit dem Sidebar Observer, welches eigentlich mit #1499 gelöst sein müsste. Kannst du gucken ob auch der Sidebar Observer gesetzt ist?

2020-11-30 18:10 UTC, 2Abendsegler commented
> Dein beschriebenes Problem klingt nach einem Problem mit dem Sidebar Observer, welches eigentlich mit #1499 gelöst sein müsste. Kannst du gucken ob auch der Sidebar Observer gesetzt ist?

Hast recht, der Sidebar Observer ist nicht gesetzt.

2020-11-30 18:23 UTC, capoaira commented
> > Dein beschriebenes Problem klingt nach einem Problem mit dem Sidebar Observer, welches eigentlich mit #1499 gelöst sein müsste. Kannst du gucken ob auch der Sidebar Observer gesetzt ist?
> 
> Hast recht, der Sidebar Observer ist nicht gesetzt.

Hmm, ich kann das nicht nachstellen. Im aktuellen Collector wird der Sidebar Observer durch den Body Observer hinzugefügt, sobald die Sidebar existiert.

2020-11-30 18:37 UTC, 2Abendsegler approved these changes
Habe alles umgesetzt bis auf die Links die ich nicht geregelt bekommen habe. Macht aber nichts.

2020-11-30 18:38 UTC, merged

2020-11-30 18:43 UTC, Ruko2010 commented
> @Ruko2010
> Ich mach die Änderungen ... leg die Füße hoch ... 😄
> Vielleicht kann ich dann heute noch ne neue Version rausschicken, sofern ich das Problem mit dem gelegentlich fehlenden Mutation Observer bei der neuen Karte noch geregelt bekomme.

Na toll, hab grad den Laptop angemacht 😃. Aber Danke. Dann setz ich mich wieder an #843

2020-11-30 18:52 UTC, 2Abendsegler commented
> Hmm, ich kann das nicht nachstellen. Im aktuellen Collector wird der Sidebar Observer durch den Body Observer hinzugefügt, sobald die Sidebar existiert.

Ja, aber der body observer wird ja auch nicht gesetzt ... . Womöglich liegt es also doch am warten auf body. 🙄

2020-11-30 19:02 UTC, capoaira commented
> 
> 
> > Hmm, ich kann das nicht nachstellen. Im aktuellen Collector wird der Sidebar Observer durch den Body Observer hinzugefügt, sobald die Sidebar existiert.
> 
> Ja, aber der body observer wird ja auch nicht gesetzt ... . Womöglich liegt es also doch am warten auf body. 🙄

Du hattest doch geschrieben, dass nach einem verschieben der Karte, die Features laufen. Das heißt, dass der Body Observer funktioniert, ansonsten würde gar nichts laufen...

2020-11-30 19:13 UTC, 2Abendsegler commented
> Du hattest doch geschrieben, dass nach einem verschieben der Karte, die Features laufen. Das heißt, dass der Body Observer funktioniert, ansonsten würde gar nichts laufen...

Ja und Ja. Der body observer läuft erst wenn ich die Karte verschiebe. Und dadurch wird der sidebar observer angetriggert. Und dadurch wird ja auch alles nachgeholt und richtig dargestellt.
Der sidebar observer muss laufen. Es scheint dabei egal ob ich warte und ihn setze, oder ob ich auf den body warte und den body observer setze. In beiden Fällen läuft der sidebar observer.

2020-11-30 19:24 UTC, capoaira commented
Ah ok, dass heißt es ist ein einmaliges Problem. Da habe ich keine Idee, habe gerade nocheinmal sämtliche Einstellungen getestet, aber ich kann es nicht Nachstellen...