[Hide Cache] Header
2Abendsegler/GClh pull request #1549
Opened 2020-12-09 19:05 UTC by capoaira

#1542 
Leider funktioniert das prüfen auf `$('#gc-header')[0]` nicht zuverlässig. Manchmal läuft das Skript schneller als der Header von GC geladen wird. 
Da `is_page('hide_cache')` schon vergeben ist und mehrere Seiten anspricht, auf denen es dann zu Fehlern kommt, habe ich die URL mit `.match()` verwendet.

2020-12-10 03:30 UTC, 2Abendsegler requested changes
Du hast in `function is_page(name)` die Zeilen zum Owner Dashboard entfernt.
```
        case "owner_dashboard":
            if (url.match(/^\/play\/owner/)) status = true;
            break;
```
Das kann doch so gar nicht mehr funktionieren, oder steh ich auf dem Schlauch?

2020-12-10 03:32 UTC, 2Abendsegler commented
> Leider funktioniert das prüfen auf `$('#gc-header')[0]` nicht zuverlässig. Manchmal läuft das Skript schneller als der Header von GC geladen wird.

Besteht das Problem noch?

2020-12-10 07:19 UTC, capoaira commented
> 
> 
> Du hast in `function is_page(name)` die Zeilen zum Owner Dashboard entfernt.
> 
> ```
>         case "owner_dashboard":
>             if (url.match(/^\/play\/owner/)) status = true;
>             break;
> ```
> 
> Das kann doch so gar nicht mehr funktionieren, oder steh ich auf dem Schlauch?

Ich habe vergessen das zu erwähnen. Mir ist aufgefallen, dass der Part doppelt vorkommt. Den doppelten habe ich enfernt.

2020-12-10 07:29 UTC, capoaira commented
> 
> 
> > Leider funktioniert das prüfen auf `$('#gc-header')[0]` nicht zuverlässig. Manchmal läuft das Skript schneller als der Header von GC geladen wird.
> 
> Besteht das Problem noch?

Leider klappt das nicht, deswegen habe ich das in diesem Branch nicht genutz. Ich habe nur die Hide Cache Seite ergänzt.

2020-12-14 05:47 UTC, 2Abendsegler reviewed
- [ ] Eigentlich sollten wir für die neue Hide Seite auch ein is_page haben. Ich weiß aber selbst noch nicht wie es am besten ist. Vielleicht die alte hide_cache vorher auch umbenennen. Bei der Gelegenheit auch mal gerade schauen, was alles für das alte hide_cache gemacht wurde und ob wir auch für die neue Seite diese Dinge nachziehen müssen. Ich denke hier beispielsweise an die Implementierungen zur Taste F2. 
- [ ] Das mit dem zu langsamen Headeraufbau müssen wir noch klären.
- [ ] Bei mir funktionieren deine Änderungen noch nicht so richtig. Menüausrichtung und ganz rechts im Header. Warum sollte GS das auch nur einmal nicht neu entwickeln. 😂🙁
![grafik](https://user-images.githubusercontent.com/22332216/102044402-0cfb7080-3dd7-11eb-8ef6-547fa563bbd0.png)

Wenn du möchtest kannst du das Thema aber auch an mich abgeben, sonst haben wir mehr an Abstimmungsarbeit als nötig, weil ich ja selbst noch nicht weiß wie wir es machen sollten. Ich würde den jetzigen Stand dann mergen und direkt darauf aufsetzen. Was meinst du?

2020-12-14 05:57 UTC, capoaira commented
> Wenn du möchtest kannst du das Thema aber auch an mich abgeben, sonst haben wir mehr an Abstimmungsarbeit als nötig, weil ich ja selbst noch nicht weiß wie wir es machen sollten. Ich würde den jetzigen Stand dann mergen und direkt darauf aufsetzen. Was meinst du?

Machen wir so 👍🏻

2020-12-14 06:01 UTC, 2Abendsegler approved these changes

2020-12-14 06:01 UTC, merged