[New profile] Links on new profile page to found and hidden caches don't work with user with special characters.
2Abendsegler/GClh pull request #1555
Opened 2020-12-14 10:37 UTC by 2Abendsegler

Use function urlencode for the username.

Steps to reproduce: See Issue #1554

2020-12-14 10:38 UTC, 2Abendsegler commented
@capoaira 
Moin, kannst du kurz drüberflitzen, ob es so passt?
(Steps to reproduce: See Issue #1554)

2020-12-14 19:00 UTC, capoaira requested changes
Bei mir haben die meisten Namen mit Sonderzeichen funktionert, allerdings
[Per + Marc](https://www.geocaching.com/p/default.aspx?u=Per%20%2B%20Marc) funktionert nicht. Dort müssten die Leerzeichen auch noch durch `%20` oder `+` ersetzt werden.

2020-12-15 05:31 UTC, 2Abendsegler commented
@capoaira 
Kannst du bitte noch mal drüberschauen.

Das plus Zeichen wird nun auch berücksichtigt.
Habe alle Umsetzungen mit urlencode geprüft.

2020-12-15 17:14 UTC, capoaira approved these changes
Perfekt, funktioniert

2020-12-15 17:21 UTC, merged