Issue #1622 New Helpful Buttons not working after loading more logs
2Abendsegler/GClh pull request #1626
Opened 2021-03-18 19:58 UTC by Ruko2010

Simple and easy fix.
Die Parameter wurden nicht an die Subfunktion weitergegeben und darum konnte nicht darauf zugegriffen werden.

2021-03-19 15:13 UTC, 2Abendsegler requested changes
Ja, das war schon mal super. 
Das reicht aber noch nicht.

- Nimm dir mal einen Cache mit mehr als den zuerst dargestellten Logs.
- Wähle dann Button "Show all logs".
- Danach funktionieren die Buttons in keinem Log mehr.

2021-03-27 19:49 UTC, 2Abendsegler commented
@Ruko2010 
Hast du den Kommentar von capoaira aus #1622 gesehen? Vielleicht hängt es damit zusammen.
`I think GS changed the template and this could be the reason.`

2021-04-22 19:21 UTC, Ruko2010 commented
Ich weis es ist schon ein wenig Zeit vergangen, aber heute klappt es endlich mal wieder, dass ich hier rein schauen kann.
@2Abendsegler ich bin gerade im Master, und bei mir funktionieren die Button sowohl beim Laden der Seite, also auch wenn ich nach unten scrolle und dann mehr logs geladen werden.
Mir fehlen aber auch die Button von GClh über den Logs, um alle Logs auf einmal zu laden....ist da was kaputt?
![image](https://user-images.githubusercontent.com/2239440/115773505-b0c1e200-a3b0-11eb-84e4-3fae2ff0d815.png)

2021-04-22 19:26 UTC, Ruko2010 commented
Ich sehe gerade, dass der GClh gar nicht läuft und deswegen die Button funktionieren 😅

2021-05-08 15:02 UTC, 2Abendsegler commented
@Ruko2010 
Ich habe den weiteren Fehler zufällig gefunden. Das Thema ist also erledigt. 
Ich baue deine Änderungen noch bei mir ein und lösche diesen PR, das geht schneller.

Das hier ist die Kleinigkeit:

```
alt:            if ($('#cache_logs_container #sortOrder').length) isUpvoteActive = true;
neu:            if ($('#cache_logs_container .sort-logs').length) isUpvoteActive = true;
```
Das ist halt GS.

2021-05-08 15:02 UTC, closed without merging