fix hide sidebar by default on list view
2Abendsegler/GClh pull request #1628
Opened 2021-04-14 18:10 UTC by capoaira

#1627

2021-04-22 14:49 UTC, 2Abendsegler commented
@capoaira 
Ich hatte noch etwas gewartet um auch deine Erweiterungen mit in die neue Version zu nehmen. Die Search Map steht aber immer noch nicht zur Verfügung. Deine Erweiterungen müssen also noch warten.

2021-04-25 20:30 UTC, 2Abendsegler requested changes
Hey,
das war Blödsinn was ich zuletzt geschrieben hatte, hab erst jetzt verstanden wie es läuft, sorry.
Mach bitte deine letzten Änderungen wieder rückgängig.

2021-04-26 11:47 UTC, capoaira commented on gc_little_helper_II.user.js
> +                if (document.location.href.match(/\.com\/play\/map(\/BM|\?bm=|\/lists)/)) hideSidebar();
> Das hier kann das Setzen der Filter behindern. Deshalb darf erst nach dem tatsächlichen Setzen der Filter ein Hide stattfinden. In setFilter wird gegebenenfalls gewartet bis die Filter da sind.

Bei BMs müssen doch keine Filter gesetzt werden.

2021-04-26 11:51 UTC, capoaira commented
> Hey,
> das war Blödsinn was ich zuletzt geschrieben hatte, hab erst jetzt verstanden wie es läuft, sorry.
> Mach bitte deine letzten Änderungen wieder rückgängig.

Bei mir waren die letzten Änderungen nötig, da die Sidebar eingeklappt wurde bevor überhaupt Inhalt sichtbar wurde. Dann war sie aber wieder ausgeklappt. Ich habe keine Möglichkeit gefunden das zu umgehen. Auf den Inhalt zu prüfen hat nicht gehofen. Deswegen die feste Zeitangabe.

2021-04-26 17:22 UTC, 2Abendsegler commented
> Bei mir waren die letzten Änderungen nötig, da die Sidebar eingeklappt wurde bevor überhaupt Inhalt sichtbar wurde. Dann war sie aber wieder ausgeklappt. Ich habe keine Möglichkeit gefunden das zu umgehen. Auf den Inhalt zu prüfen hat nicht gehofen. Deswegen die feste Zeitangabe.

Ok, verstehe.

Wenn keine Bookmarklisten, addieren sich aber nun Zahlen beim Schließen der Sidebar. 

Irgendwie ist das Ganze Verfahren etwas unbefriedigend, weil bei mir auch beispielsweise immer mal wieder die Fund Icons auf der Karte und/oder in der Cache Liste verbleiben, obwohl sie laut Filter ausgeblendet werden sollten, dort also tatsächlich auch entsprechend markiert sind.

Lass mich auch mal noch überlegen wie wir das stabiler machen können.

2021-04-27 04:03 UTC, 2Abendsegler approved these changes
So, ich merge das jetzt mal.
Werde dann anschließend noch kleine Änderungen machen.

2021-04-27 04:04 UTC, merged