[Cache listing] Change to old search on cache listing page.
2Abendsegler/GClh pull request #1691
Opened 2021-05-05 18:27 UTC by capoaira

#1682 

Eigentlich wollte ich nur kurz was machen - wie gesagt, nur lernen kann ich nicht ;)
Aber die Sonderzeichen in Namen haben es dann etwas komplizierter gemacht...

Hier kann man mit Sonderzeichen Testen:
https://coord.info/GC89TZY

2021-05-05 18:39 UTC, 2Abendsegler requested changes
Ich habe als erstes ein dynamisches (die untereren) Copy data to clipboard Feature getestet, weil ich weiß dass hier der Real Owner aus einem der von dir bearbeiteten Links ermittelt werden muss. Hatte ich im Issue beschrieben. Das läuft dann leider auf Fehler. Mehr habe ich noch nicht getestet.

2021-05-05 18:43 UTC, 2Abendsegler commented
Du kannst dir das notwendige Coding aus v0.10.12 nehmen, also aus einer Version vor den Änderungen der Links. Die Funktion heißt get_real_owner.

2021-05-05 18:45 UTC, 2Abendsegler commented
Hier ist das Coding:
```
// Searches for the owner's original username from the listing.
    function get_real_owner() {
        if ($('#ctl00_ContentBody_bottomSection')) {
            var links = $('#ctl00_ContentBody_bottomSection a[href*="/seek/nearest.aspx?u="]');
            for (var i = 0; i < links.length; i++) {
                var match = links[i].href.match(/\/seek\/nearest\.aspx\?u\=(.*)$/);
                if (match) return urldecode(match[1]);
            }
            return false;
        } else return false;
    }
```

2021-05-05 20:16 UTC, capoaira commented
Der Coding habe ich genutzt und das funktioniert auch.
Es hat etwas gedauert, aber ich habe den Bug gefunden: Bei Events gibt es keinen fav score, deswegen hat es beim Testcache nicht geklappt. Der Bug besteht aber auch im aktuellen collector.
Jetzt sollte es klappen.

2021-05-06 07:43 UTC, 2Abendsegler requested changes
Super, dass du auch den Fehler ausgemerzt hast. Ja, das war vermutlich nicht einfach zu finden.

---
Ich habe noch einige Anmerkungen. Ich glaube ich bin heute besonders genau, sorry. Eigentlich brauchst du ja etwas Entspannung, so zwischen dem Lernen. Das Issue ist aber vielleicht nicht so super dazu geeignet.

- [ ] 1. Bitte in function get_real_owner folgendes ändern (ich weiß, ist nicht von dir):
alt: `if ($('#ctl00_ContentBody_bottoXmSection')) {`
neu: `if ($('#ctl00_ContentBody_bottoXmSection')[0]) {`

- [ ] 2. Wir wollen alle Links in diesem Areal umstellen, sofern das möglich ist, nicht nur die beiden ersten.
![grafik](https://user-images.githubusercontent.com/22332216/117257903-ad1c6980-ae4c-11eb-8e70-5426982ee33a.png)

- [ ] 3. Nur ein Parameter für Public Profile und Cache Listing finde ich nicht gut. Hier brauchen wir zwei Parameter und wir müssen auch im Config an zwei Stellen dokumentieren. Also die bereits veröffentlichte Umstellung im Public Profile wie vorhanden belassen und im Cache Listing was neues machen.

- [ ] 4. Beim Umsetzen der Links machst du keine Prüfungen, das finde ich nicht gut.
Wenn es linkFound nicht gibt, dann knallt es bei Let match. 
Wenn es match nicht gibt, dann knallt es bei der Folgezeile.
Es sollte so gemacht werden wie auch in function get_real_owner. Wenn GS etwas ändert, dann sollte es nicht knallen.

2021-05-06 09:31 UTC, capoaira commented
> Ich habe noch einige Anmerkungen. Ich glaube ich bin heute besonders genau, sorry. Eigentlich brauchst du ja etwas Entspannung, so zwischen dem Lernen. Das Issue ist aber vielleicht nicht so super dazu geeignet.

Alles gut. Dachte, dass das schnell gemacht ist, weil ich sowas in der Art ja schon gemacht habe. Habe ich falsch gedacht 😅
Ich werde mal gucken wann ich hier weiter mache. Die nächsten Tage sind zum lernen reserviert.

2021-05-15 05:22 UTC, 2Abendsegler commented
@capoaira 
Ich habe deine Änderungen manuell übernommen.
Ich schließe den PR.

2021-05-15 05:22 UTC, closed without merging