Hide Header on Search Map
2Abendsegler/GClh pull request #1764
Opened 2021-05-24 13:16 UTC by capoaira

2021-05-24 15:10 UTC, 2Abendsegler requested changes
Der Wahnsinn!
Ich gebe zu, ich habs zwischendurch auch noch mal versucht, jedoch erfolglos. 
Klasse gemacht!

Nur noch zwei Kleinigkeiten:
1. Wenn man den Header wieder anschaltet, dann bleibt die Stelle des Headers zuerst mal weiß und man sieht das Ladekringel. Kannst du bitte mal schauen, ob man den Header nicht schneller wieder darstellen kann. Dann wäre kein weiß mehr da und das Ladekringel würden wir auch nicht sehen.
![GIF 24 05 2021 16-53-08](https://user-images.githubusercontent.com/22332216/119366632-75694a80-bcb1-11eb-81ae-1fa0f6ad23cb.gif)

---
2. Die Headereinstellung nimmt jetzt noch ne weitere Zeile in Anspruch. Und man kann die Einstellung auch nicht ausblenden. 2a. Fast optimal wäre es, wenn Save as PQ und Hide Header sich ne Zeile teilen. 2b. Optimal wäre es wenn man außerdem auch den Hide Header abschalten könnte. Das sollte dann ein Button sein der unterhalb von "Show button "Save as Pocket Query"". Das sollte dann auch für die alte Karte gemacht werden. Vielleicht kann du wenigstens noch 2a. machen, ich könnte mich dann auch noch um 2b kümmern.

---
Was willst du eigentlich studieren? Irgend etwas in der IT Branche wäre vielleicht keine schlechte Idee. Obwohl ich ja gar nicht abschätzen kann, ob du nicht vielleicht auch noch ganz andere Talente hast. 😊

2021-05-24 17:07 UTC, capoaira commented
Zu 1: Da recht sich das blinde Kopieren des `toggle('slow')` ;)

Zu 2: Es gab jetzt doch mehr zu beachten, als ich gedacht habe... Aber ich habe alles erledig (hoffentlich)

> Was willst du eigentlich studieren? Irgend etwas in der IT Branche wäre vielleicht keine schlechte Idee. Obwohl ich ja gar nicht abschätzen kann, ob du nicht vielleicht auch noch ganz andere Talente hast. 😊

Jip, ich will Informatik studieren.

2021-05-24 17:56 UTC, capoaira commented
Hier habe ich `improveAddtolistPopup()` verschoben, damit Save as PQ und Hide Header untereinander stehen, da bei Funktionen aus der selben funktion herraus aufgerufen werden.

2021-05-25 08:57 UTC, 2Abendsegler approved these changes
Klasse gemacht mit der Actionbar und auch die Abhängigkeiten. Und das eigentliche Thema "Hide Header" ja sowieso. 
Danke für die tolle Arbeit!

2021-05-25 09:10 UTC, 2Abendsegler commented
Hier bestehen noch Konflikte. Ich habe erfolglos versucht das übers GitHub Desktop zu bereinigen. Da laufe ich auf einen Fehler:
`Couldn't find branch 'new-map/hide-header' in remote 'github-desktop-capoaira'. A common cause for this is if the PR author has deleted their branch or their forked repository.`
Kannst du mal schauen, ob du den Konflikt irgendwie ausräumen kannst.

2021-05-25 09:39 UTC, capoaira commented
Habe es geschafft :)

2021-05-26 04:37 UTC, merged

2021-05-26 04:38 UTC, 2Abendsegler commented
@capoaira 
> Habe es geschafft :)

Sehr cool!