Pq set defaults
2Abendsegler/GClh pull request #1780
Opened 2021-05-30 08:09 UTC by 2Abendsegler

[Search Map / Browse Map / Pocket Query] Before saving as PQ from map, determine whether the GClh default settings for new PQs should be set or not.
#1574

2021-05-30 08:18 UTC, 2Abendsegler commented
@capoaira 
Kannst du bitte mal drüber schauen?

Ich musste auch noch Einiges ändern in deinem Coding zu "Save as PQ from Search Map". Wenn die Defaults gesetzt werden, dann reicht es nicht aus, wenn ein Parameter nur per Click gesetzt wird, weil er ja durch die Defaults schon gesetzt sein kann. Man muss also genau einen Wert setzen, checked oder eben nicht checked.

Den `toggle-handle` (umbenannt in `gclh_toggle-handle`) habe ich in `gclh_defi.js` gelegt, weil ich ihn bei der Browse Map auch noch verwendet habe.

Bitte beachte beim Testen, dass auch `gclh_defi.js` geändert wurde.

2021-05-30 09:08 UTC, capoaira requested changes
Die Änderung sehen gut aus und funktionieren. Ich habe aber eine Anmerkung:

"Is Enabled" funktionert nicht wenn man von der neuen Karte kommt, da der Fliter bei der neuen Karte automatisch auf "alle" steht.
Ich würde noch einen Hinweis übernehmen, dass die Karte Einstellung die GClh default Werte überschreiben.
Dann haben wir aber das debakel, dass "Is Enabled" auf der neuen Karte immer überschrieben wird. Oder der Hinweis bei "Is Enabled" nicht stimmt. Ich sehe auf der Karte gerne die disabledten Caches, auf meinem GPS bei der Cachetour aber ungern. Ich weiß nicht ob ich da ein Einzelfall bin.
Hierfür müssten wir meiner Meinug nach noch eine Lösung finden.

2021-05-30 09:11 UTC, capoaira requested changes
Oh, mir ist gerade nochetwas aufgefallen: Der Toggel springt immer auf false, beim reload der Seite, aber auch wenn ich einen Cache anklicke oder Filter setzte.
Hier sollte bei jedem Ändern der Status (true/false) gespeichert werden, so dass es sich nicht zurücksetzt.

2021-05-30 10:23 UTC, 2Abendsegler commented
Danke schon mal für die Tests.

> Ich würde noch einen Hinweis übernehmen, dass die Karte Einstellung die GClh default Werte überschreiben.

Ich habe das im title von `Set defaults` hinzugefügt. Hover mal.

> Oh, mir ist gerade nochetwas aufgefallen: Der Toggel springt immer auf false, beim reload der Seite, aber auch wenn ich einen Cache anklicke oder Filter setzte.
> Hier sollte bei jedem Ändern der Status (true/false) gespeichert werden, so dass es sich nicht zurücksetzt.

Klar, gut aufgepasst. Erledigt.

> "Is Enabled" funktionert nicht wenn man von der neuen Karte kommt, da der Fliter bei der neuen Karte automatisch auf "alle" steht.

Das habe ich nicht verstanden. Das ist doch nichts anderes als beispielsweise beim `Found status`. Der steht auch auf `All` und überschreibt damit die Defaults. So soll es doch sein. Wenn du die Caches mit `Is Enabled` haben möchtest, dann musst du es im Filter wählen. Irgendwie stehe ich auf dem Schlauch. 🙄

2021-05-30 10:51 UTC, capoaira commented
> Das habe ich nicht verstanden. Das ist doch nichts anderes als beispielsweise beim Found status. Der steht auch auf All und überschreibt damit die Defaults. So soll es doch sein. Wenn du die Caches mit Is Enabled haben möchtest, dann musst du es im Filter wählen. Irgendwie stehe ich auf dem Schlauch. 🙄

Klar, das Verhalten an sich ist richtig, aber unterscheidet sich zur Browsemap. Bei der neuen Karte wird immer "alle" angegeben. Ich finde es beim Planen gut zu sehen welche Caches disabled sind (wenn es viele sind fahre ich woanders hin). Wenn ich dann eine PQ erstelle will ich die disabledten nicht sehen, weil das ja die Cache sind die ich besuchen will. Dann müsste ich vorher noch den Filter setzten oder es auf der PQ Seite hinzufügen. (Klar, ist eigentlich kein großer Aufwand ;))

Vielleicht könnten wir im Config für "Is Enabled" einen Parameter "Do not override this default value" machen.

2021-05-30 11:03 UTC, 2Abendsegler commented
Verstehe.

Man könnte hingehen und die Parameter mit All als nicht gesetzt werten. Dann könnte man sich auf der Karte auch die Founds mit ansehen und über die Defaults würden die Founds dann rausfliegen. Das würde ich als hilfreich empfinden, weil man dann sieht ob man schon mal in der Nähe unterwegs war.

Das müsste dann aber für alle Alls gelten.

2021-05-30 11:35 UTC, capoaira commented
> Man könnte hingehen und die Parameter mit All als nicht gesetzt werten. Dann könnte man sich auf der Karte auch die Founds mit ansehen und über die Defaults würden die Founds dann rausfliegen. Das würde ich als hilfreich empfinden, weil man dann sieht ob man schon mal in der Nähe unterwegs war.

Das Finde ich gut

Die Anpassungen habe ich getestet und die funktionieren auch super.

2021-05-31 08:37 UTC, 2Abendsegler commented
Es gibt nun einen neuen Parameter im Config der ermöglicht, dass die "All" Einstellungen aus dem Karten Filter gesetzt oder nicht gesetzt werden. Entsprechend ist auch dein "is enable" Wunsch nun möglich.
![grafik](https://user-images.githubusercontent.com/22332216/120165588-041f1f80-c1fc-11eb-88a7-2cb439104a3c.png)

Kannst du bitte noch mal kurz drüber schauen?

2021-05-31 09:48 UTC, capoaira approved these changes
Sieht gut aus

2021-05-31 09:53 UTC, merged