[Owner Dashboard] Compact Layout
2Abendsegler/GClh pull request #1794
Opened 2021-06-05 12:16 UTC by capoaira

#1370

Ich habe vorallem in der sidebar die Abstände verringert. Bei den Logs wird mir vieles zu unübersichtich, wenn dort mehr zusammenfassen würde.

2021-06-05 16:01 UTC, 2Abendsegler requested changes
Hmm, wenn ich ehrlich bin, ist hier noch ziemlich viel nicht ok. 

Die Anzahl Cahces an den verschiedenen Stellen stehen nicht mehr untereinander. 
Die Symmetrie der Felder nach oben bzw. unten und nach den Seiten ist nicht mehr identisch. Das sieht komisch aus. Auf mich wirkt es ein wenig so, als ob du in Zeitdruck wärst und es noch schnell fertig machen wolltest. 
Ich finde es so nicht schön.

![Screenshot 2021-06-05 at 17-30-50 Geocaching com](https://user-images.githubusercontent.com/22332216/120897576-2dd6ad00-c627-11eb-8765-911ea8a73f43.jpg)

---
Außerdem ist die Darstellung immer noch nicht stabil. Verwendet man den Zoom wird alles mögliche verschoben und auch nicht mehr an die gleiche Stelle zurück gerückt wenn man den Zoom wieder zurücknimmt. 
Das ist auch nicht schön.

Irgendwie scheint die Seite furchtbar anfällig auf Änderungen.

![GIF 05 06 2021 17-47-34](https://user-images.githubusercontent.com/22332216/120897560-1bf50a00-c627-11eb-81a4-8b1df83990f5.gif)

2021-06-05 17:06 UTC, capoaira commented
> Das sieht komisch aus. Auf mich wirkt es ein wenig so, als ob du in Zeitdruck wärst und es noch schnell fertig machen wolltest.

Ne, unter Zeitdruck stehe ich nicht. Ich weiß ja, was ich nicht schaffe mache ich später. 
Ich habe ja schon vor einer Ewigkeit mit diesem Issue angefangen und es heute fertig gemacht. Da habe ich wohl nicht so genau auf das geguckt, was ich bereits gemacht hatte. Ist aber genauso blöd :(. Ich bessere da nochmal nach.

>Außerdem ist die Darstellung immer noch nicht stabil. Verwendet man den Zoom wird alles mögliche verschoben und auch nicht mehr an die gleiche Stelle zurück gerückt wenn man den Zoom wieder zurücknimmt.
Das ist auch nicht schön.

Hier habe ich gerade mal nach dem Fehler gesucht. Der hat nichts mit dem Compact Layout zu tun, sondern mit dem einer Zeile aus dem VipVupMail gedöns... ich gucke mir auch das nochmal genauer an....

2021-06-07 14:24 UTC, capoaira commented
Ich habe nun meine Änderungen commited. Wenn noch etwas fehlt dauert es, bis ich es nachbessern kann. Ab morgen bin ich im Urlaub, ohne Laptop :)

2021-06-07 14:26 UTC, 2Abendsegler commented
> Ab morgen bin ich im Urlaub, ohne Laptop :)

Dann viel Spaß im Urlaub!

2021-06-08 11:30 UTC, 2Abendsegler approved these changes

2021-06-08 11:31 UTC, merged