previewmap in oldstyle & personal cache notes to monospace
2Abendsegler/GClh pull request #1858
Opened 2021-07-29 16:11 UTC by LittleJohn-DD

Ändert in über die config (Schalter), dass in der Übersichtskarte der link zur alten Kartendarstellung erfolgt, sowie die Schriftart der Personalnote auf Monospace geändert wird.

2021-08-05 09:33 UTC, capoaira commented
#1859 
#1860

2021-08-05 10:54 UTC, capoaira requested changes
Moin,
die Funktionen an sich funktionieren gut. Mir sind jedoch 2 Sachen im Coding aufgefallen, die noch angepasst werden sollten, damit es einheitlicher ist:
1. Wir nutzen 4 Leerzeichen anstatt eines Tabs
2. Bei uns werden neuen Config Parameter immer unten in der Liste angefügt. (Oben bei `c.settings_` und unten bei den `var checkboxes`)


Es scheint auch ein Problem mit den Branches bzw. Versionen zu geben. Einige Änderungen, die hier angezeigt werden, sollten eigentlich schon im collector sein. @2Abendsegler hast du eine Idee, woran das liegt?

2021-08-05 11:02 UTC, LittleJohn-DD commented
Hi,
OK, verstanden.
Passt du das an oder soll ich nochmal an den Code?

Zu deiner Frage an  Abendsegler:
Vielleicht liegt es daran, dass ich bei den forks und umgekehrt irgendwie etwas falsch eingestellt oder ... gemacht habe.
Ich denke, ich mache eine ganz neuen Fork nach der nächsten Aktualisierung. Bin recht unerfahren innerhalb GitHub 🙄

2021-08-05 11:19 UTC, capoaira commented
Ich kann das auch machen, wenn du willst. Wir sollten aber so oder so warten, bis die Sache mit den Versionen geklärt ist. 

Am Anfang hatte ich auch eine Menge Probleme mit GitHub und habe meinen Fork sogar mehrfach kaputt gespielt, sodass ich einen neuen machen musste.
Mittlerweile komme ich mit einem Mix von GitHub Desktop und GitKraken ganz gut klar (und trotzdem habe ich immer mal wieder Probleme).
Ich würde dir auch GitKraken empfehlen, damit kannst du deine Branches immer wieder auf den Stand eines anderen Braches (z.B. collector) bringen (rebase). Eine Anleitung dazu hat mir Ruko2010 geschrieben. Ich gucke mal, ob ich die wiederfinde.

2021-08-05 12:07 UTC, capoaira commented
So, ich habe zwar die Anleitung nicht gefunden, aber herausgefunden, dass ich bei deinem Fork einen rebase durchführen kann. Ich habe das mal gemacht und hoffe, dass das für dich ok ist. Jetzt werden auch nur deine Änderungen angezeigt.
Vielleicht schaffe ich es heute Abend, eine kleine Anleitung zu schreiben, wie der Rebase mit GitKraken funktioniert. Mit GitHub Desktop kriege ich das nämlich nie hin ;)

Möchtest du die Kosmetik (Punkt 1 und 2) ändern?

2021-08-05 12:12 UTC, capoaira commented on gc_little_helper_II.user.js
> +            template += '    <a target="_blank" href="https://coord.info/{{geocache.referenceCode}}">';
Ich bin mir nicht sicher, ob diese Änderung notwendig ist. Man kann den Cache bereits im neuen Tab öffnen, wenn man den Pfeil anklickt. 
![grafik](https://user-images.githubusercontent.com/50927164/128347538-796374a4-974c-4e0c-9b5b-1db59f699d91.png)
Mit dieser Änderung würdest du die Möglichkeit nehmen, den Cache im selben Tab zu öffnen.

2021-08-05 14:57 UTC, LittleJohn-DD commented on gc_little_helper_II.user.js
> +            template += '    <a target="_blank" href="https://coord.info/{{geocache.referenceCode}}">';
JA, du hast natürlich recht, sorry.

2021-08-05 14:59 UTC, LittleJohn-DD commented
> 
> 
> So, ich habe zwar die Anleitung nicht gefunden, aber herausgefunden, dass ich bei deinem Fork einen rebase durchführen kann. Ich habe das mal gemacht und hoffe, dass das für dich ok ist. Jetzt werden auch nur deine Änderungen angezeigt.
> Vielleicht schaffe ich es heute Abend, eine kleine Anleitung zu schreiben, wie der Rebase mit GitKraken funktioniert. Mit GitHub Desktop kriege ich das nämlich nie hin ;)
> 
> Möchtest du die Kosmetik (Punkt 1 und 2) ändern?

Mach du das bitte, dann ist es gleich an der richtigen Stelle.
Ich ändere dann auch nichts mehr an meinem code und warte das nächste release ab.
Einverstanden?

2021-08-05 15:19 UTC, LittleJohn-DD commented
🙏👍👍👍

2021-08-05 15:23 UTC, capoaira commented
Ok, ich habe es gemacht.

Bitte lass dich von der "Kritik" nicht einschüchtern. Es ist nicht Böse gemeint und vieles kannst du auch noch gar nicht wissen, da du ja noch neu bei uns mit machts (und der Coding style und Workflow kann bei anderen Projekten auch anders aussehen).
Die Funktion an sich funktioniert ja super.

Du musst auch nicht unbedingt das nächste release abwarten. Einfach weiter machen und bei Fragen fragen. 
Wir freuen uns immer über Input und Unterstützung.

2021-08-05 15:26 UTC, LittleJohn-DD commented
Nee, alles gut.
Ich finde Kritik immer gut - nur damit kann man sich verbessern.

Danke

2021-08-10 20:25 UTC, 2Abendsegler approved these changes
Die Anpassungen funktionieren. Ich habe aber noch ein paar Änderungen gemacht. Und erstmalig habe ich aus dem GitHub Desktop heraus eine eigene Branch in einen fremden PR gemerged, so dass wir nur einen einzigen PR haben mit allen Änderungen.

Im wesentlichen habe ich drei Änderungen gemacht:
- Während der Eingabe des Textes wird der Text auch in Monospace angezeigt.
- Das Entfernen der Unterstriche im Text habe ich schon an einer anderen Stelle eingebaut. Hier habe ich es deshalb wieder entfernt.
- Beide Parameter habe ich auf false gesetzt, weil das meines Erachtens am ehesten einem Standard User entspricht. 

Ansonsten habe ich die Texte im Config noch überarbeitet, was ja aber sowieso immer Geschmacksache ist.

Ist damit approved, danke an euch beide.

2021-08-10 20:27 UTC, merged