[Statistik Matrix] Possible D/T combinations no longer works.
2Abendsegler/GClh pull request #1964
Opened 2021-12-06 19:37 UTC by capoaira

#1959

2021-12-07 16:13 UTC, 2Abendsegler requested changes
Das war eine gute Idee, leider funktioniert es so aber nicht.

Wenn du in der Liste der Caches bist, ist das `&gclh=GClhMatrix` im Link zur Karte nicht mehr vorhanden. Wenn du den Kartenlink anwählst und die Karte etwas bewegst, läuft die automatische Selektion los und ändert die Anzeige auf der Karte. Obwohl du beispielsweise einen Suchradius von 100 km für die möglichen Kombinationen angegeben hast, werden dadurch nur noch die Caches in einem Suchradius von, ich glaube, 16 km angezeigt. Und wenn du herauszoomst werden immer mehr Caches angezeigt, auch über den Suchradius von 100 km hinaus. Hier sollte die automatische Selektion nicht anlaufen, so wie auch beispielsweise bei Bookmarklisten. 

Mein Vorschlag aus dem Issue funktioniert aber auch nicht oder nicht mehr richtig, weil auch das `#GClhMatrix` durch bewegen oder durch zoomen auf der Karte entfernt wird, und das `#GClhMatrix` wohl immer wieder neu überprüft wird (Observer).

2021-12-07 17:09 UTC, capoaira commented
Hm, das ist mir gar nicht als Problem aufgefallen. Ich finde gut, wenn beim rauszoomen weiter geladen wird. Das wäre ja quasi, wie wenn der Filter Manuel gesetzt werden würde. Aber das ist Geschmackssache. 
Ich gucke mir das die Tage nochmal an...

2021-12-11 10:24 UTC, capoaira commented
Moin,
ich habe gerade versucht das zu vermeiden, allerdings zoomt die Map bei mir nicht, wenn man einen Radius angibt. Sowohl mit GClh, als auch ohne. Ich habe es erst von der Suche aus versucht, dann direkt in der Map den Radius verändert. Ergebnis: Nichts.
Zwischendrin lädt er dann mal die Caches im angegebenen Umkreis, aber nicht immer. Ich denke da liegt irgendein Fehler bei GS... :(

2021-12-11 10:36 UTC, 2Abendsegler commented
Ja, die Karte zoomt nicht mehr heraus, war mir auch aufgefallen. Finde ich aber nicht so schlimm. Wichtig wäre es, dass alle Caches im Umkreis geladen werden. Doof dass es hier Probleme gibt.
Stell doch bitte mal deine Anpassungen in einen PR, ich schau mir das dann auch noch mal an. Vielleicht fällt mir noch was auf.

2021-12-11 11:04 UTC, capoaira commented
Ich habe noch keine Anpassungen gemacht. Mit dem testen wollte ich eigentlich Lösung finden. Für mich hat es aber nur Hürden gebracht. 
Ich habe nochmal weiter getestet und mein oben beschriebener Bug von GS scheint doch nur die Karte selber (ohne Skripts) zu treffen. Die Links würden funktionieren. Da habe ich wohl vorschnell die falschen Schlüsse gezgen :( ...
Das automatische neu laden kann ich aber leider immer noch nicht abstellen. Die Karte prüft, ob die angegebenen User existieren und schmeißt alle unbekannten Parameter raus...
Ich muss noch etwas experimentieren ...

2021-12-11 11:43 UTC, capoaira commented
So, jetzt klappt es bei mir.
Da die Karte alles entfernt, speichern wir uns nun in einer Variable, ob es die D/T Statistik Map ist.
Zusätzlich ist mir noch aufgefallen, dass man nicht mehr automatisch auf die Map weitergeleitet wird, auch wenn man es ausgewählt hat. Das wird in Linie 10660 bzw. 10662 gefixt.

2021-12-18 19:08 UTC, 2Abendsegler requested changes
Die eigentlichen Dinge funktionieren jetzt, auch die Weiterleitung auf die Karte, super.

Sobald auf dem Kartenausschnitt keine relevanten Caches vorhanden sind, werden die gefundenen Caches, die über den Kartenausschnitt hinausgehen zwar kurz in der Liste angezeigt, verschwinden dann aber wieder und kommen auch nicht wieder wenn man herauszoomt. Ich habe versucht herauszufinden, woran es hängt, konnte aber nichts finden.

Kannst du vielleicht nochmal schauen?

Hier eine Aufzeichnung:
![GIF 18 12 2021 20-02-02](https://user-images.githubusercontent.com/22332216/146653004-e0fbe57a-2764-48cd-b87f-ba6828f36f8e.gif)

(Sorry, hat etwas gedauert bis ich wieder Lust hatte hier was zu machen. 🙄)

2021-12-20 10:45 UTC, capoaira commented
> (Sorry, hat etwas gedauert bis ich wieder Lust hatte hier was zu machen. 🙄)

Dafür warst du nun umso fleißiger....

2021-12-20 10:46 UTC, capoaira commented
So, jetzt sollte es klappen. Durch das Setzten der default Filter hat es nicht geklappt...

2021-12-20 14:12 UTC, 2Abendsegler approved these changes
Ja, super gefunden!

2021-12-20 14:12 UTC, merged