+Back to drafst with f2
2Abendsegler/GClh pull request #2059
Opened 2022-02-22 00:16 UTC by king-ton

Gleich noch was kleines. Nach eines Absenden einer "neuen" Draft kommt man direkt wieder ins Listing. Wird der Drafts Hinweis angezeigt, kann man mit F2 nun wieder zu den Drafts navigieren (sicherlich kann man das auch automatisiert machen? Aber dafür stecke ich zu wenig in der Materie dieses Skripts)

2022-02-22 08:43 UTC, 2Abendsegler requested changes
Moin nochmal,

danke für deine Arbeit.

Die Personal Cache Note im Listing wird mit F2 gespeichert. Mit deiner Änderung wäre das nicht mehr möglich. Diese Änderung können wir so nicht übernehmen. 

Dieses Feature, nach dem Absenden des Logs auf die Draft Seite zurückkehren, ist in der Liste von Groundspeak enthalten. Wir sollten noch etwas abwarten und Groundspeak noch etwas Zeit geben, die Anforderungen umzusetzen, auch wenn es ziemlich nervig ist mit den derzeitigen Seiten zu arbeiten.

LG
Frank

2022-02-22 09:30 UTC, capoaira commented
> sicherlich kann man das auch automatisiert machen?

Jip, dazu kann man in diesem Fall zwei Wege benutzen:
1. Die `click()` Funktion 
2. `document.location = ` (in diesem Fall glaube ich die schönere Methode) 

Ich würde jedoch auch noch warten, bis GS die Liste abgearbeitet hat, bzw eindeutig nicht mehr dran arbeitet.

2022-03-13 10:49 UTC, king-ton commented
Das ist so gebaut, dass dann der Mechanismus von den Notes nicht mehr greift, sobald man per Draft im Listing ist.
Klar könnte man auch bauen, dass man direkt wieder zu den Drafts geleitet wird.

Ich finde den Flow persönlich so sehr gut, dass man immer per F2 weiter kommt bzw. zur nächsten Seite kommt.
Könnt mir auch vorstellen dies auf der Drafts-Seite zu machen. Wenn man F2 drückt, kommt man automatisch zum Loggen des ersten Caches. Aber das ist ein anderes Thema :)

2022-03-13 23:29 UTC, 2Abendsegler commented
Moin,

die F2 Taste können wir an dieser Stelle doch nicht benutzen, hatte ich oben bereits beschrieben, weil dann ein Speichern der Personal Cache Note mit F2 nicht mehr möglich wäre.

Versuch es mal: Wenn du nach dem Loggen ins Cache Listing kommst, dann klick mal in die Personal Cache Note, trag etwas ein und drücke F2 zum Speichern. Du wirst dich dann bei den Drafts wiederfinden, obwohl du nur die Personal Cache Note speichern wolltest. 

Auch wenn der Flow mit F2 sicherlich ganz nett wäre, verwenden wir die F2 Taste bisher ausschließlich zum Speichern.

Ich würde es schön finden, wenn eine automatische Weiterleitung zur Draft Seite erfolgen würde, sofern man einen entsprechenden Parameter im Config gesetzt hat. Oder noch viel besser, wenn man gar nicht erst ins Cache Listing kommt, sondern direkt zur Draft Seite, falls das möglich ist, was ich im Moment nicht beurteilen kann. Denkbar wäre auch ein Click Event oben in der Nähe der Nachricht im Cache Listing, wenn man es denn nicht automatisch machen möchte.

2022-04-07 10:36 UTC, capoaira commented
Moin,
ich habe das Feature ohne F2 Taste eingebaut (#2098), daher schließe ich diesen offenen PR

2022-04-07 10:36 UTC, closed without merging