Filtersets
2Abendsegler/GClh pull request #2102
Opened 2022-04-03 13:10 UTC by capoaira

#2055
#1504

An sich funktioniert denke ich alles, es muss aber noch ausführlich getestet werden.
Die Map zoom immer raus, da will ich gucken, ob ich das noch in den Griff kriege ;)

2022-04-28 19:50 UTC, LittleJohn-DD commented
Hallo,

Entschuldigen Sie bitte. Ich kenne Ihren Namen nicht.
Mein Mann ist letzte Woche verstorben.

Freundliche Grüße
Carina Rossille

2Abendsegler ***@***.***> schrieb am Do., 28. Apr. 2022,
21:44:

> Ich hatte die letzten Tage keine Zeit, ich hatte nur mal kurz
> reingeschaut. Bin jetzt noch einige Tage in Urlaub. Hoffe wenn ich zurück
> bin, dass ich dann endlich dran gehen kann. Hast du schon gut getestet?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/2Abendsegler/GClh/pull/2102#issuecomment-1112590867>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF6XMLKNKO4MPX2JU5ZEMP3VHLTA5ANCNFSM5SNFSIEQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-04-28 20:43 UTC, 2Abendsegler commented
Hallo Carina,

das tut mir sehr leid, Herzliches Beileid!

Patrick hatte sich im Script "GC little helper II" als Beobachter eingetragen. Das führt dazu, dass alle Beiträge zum Script an seine Mail Adresse gesendet werden. Ganz unten in jeder Mail gibt es einen "unsubscribe" Link. Damit kann man die Beobachtung beenden, hoffe ich. Bitte versuch es mal. Wenn du danach immer noch Mails von uns bekommst, dann kannst du dich gerne direkt über die Mail Adresse eifra@web.de bei mir melden.

Liebe Grüße
Frank

2022-04-29 05:38 UTC, LittleJohn-DD commented
Hallo Frank,

ja, das hat er wirklich gern gemacht. Danke für die Info.
Ich werde versuchen die Mails abzubestellen.

Alles Gute.
Carina

2Abendsegler ***@***.***> schrieb am Do., 28. Apr. 2022,
22:43:

> Hallo Carina,
>
> das tut mir sehr leid, Herzliches Beileid!
>
> Patrick hatte sich im Script "GC little helper II" als Beobachter
> eingetragen. Das führt dazu, dass alle Beiträge zum Script an seine Mail
> Adresse gesendet werden. Ganz unten in jeder Mail gibt es einen
> "unsubscribe" Link. Damit kann man die Beobachtung beenden, hoffe ich.
> Bitte versuch es mal. Wenn du danach immer noch Mails von uns bekommst,
> dann kannst du dich gerne direkt über die Mail Adresse ***@***.*** bei
> mir melden.
>
> Liebe Grüße
> Frank
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/2Abendsegler/GClh/pull/2102#issuecomment-1112637073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF6XMLJKHD2Z7NEWCHTGESLVHLZ7XANCNFSM5SNFSIEQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-04-29 12:00 UTC, capoaira commented
> Ich hatte die letzten Tage keine Zeit, ich hatte nur mal kurz reingeschaut. Bin jetzt noch einige Tage in Urlaub. Hoffe wenn ich zurück bin, dass ich dann endlich dran gehen kann. Hast du schon gut getestet?

Jip, eigentlich habe ich alles gut getestet.

Genieße deinen Urlaub ;)

2022-05-02 09:34 UTC, 2Abendsegler requested changes
Hier hast du ganz schön viel Arbeit reingesteckt. Mir war nicht klar, dass hier so viel geändert werden muss.

Ich habe bisher nur ein paar Tests mit überschaubaren Einstellungen auf der Karte gemacht. 

Ich habe im Filter als Location Bremen eingegeben, habe Cache Type Multi ausgewählt und mir dann das Ergebnis angesehen. Dann bin ich noch mal in den Filter rein und habe ein Filterset dazu angelegt.
![0](https://user-images.githubusercontent.com/22332216/166214147-11af346a-ec27-4e3b-8126-3f554d89041a.JPG)

Wenn ich das Filterset nun auswähle steht in der Location Bremen, es werden aber Multis meiner Homekoordinaten in der Liste angezeigt und die Karte steht auch dort. 
![1](https://user-images.githubusercontent.com/22332216/166213326-64c55bf0-7719-4d06-87ed-5bbc4d42ba7e.JPG)

Rufe ich jetzt die Filter auf, steht als Location Bremen, es sind aber keine Cache Types selektiert. Vor Bremen steht auch nicht Region sondern Query.
![2](https://user-images.githubusercontent.com/22332216/166213543-f2cdd6b5-22dc-406e-8b76-27acc6d555dc.JPG)

Außerdem ist mit aufgefallen, dass die Filtersets nicht mehr sortiert werden, sondern in der Liste unten angehängt werden.

2023-02-08 15:40 UTC, closed without merging

2023-02-08 16:31 UTC, 2Abendsegler commented
@capoaira 
Moin, 

ich habe gerade diesen PR gelöscht. 

Ich habe Probleme den "gc_little_helper_II.user.js" im collector zu aktualisieren. Ich kann die Änderungen zwar im merge (also hinter dem Namen "gc_little_helper_II.user.js") sehen, der "gc_little_helper_II.user.js" wird aber nicht aktualisiert. Selbst wenn ich den "gc_little_helper_II.user.js" direkt in den collector uploade passiert nichts. Als letztes Mittel habe ich eben den collector gekillt und dann aus dem master neu aufgebaut. Half aber auch nichts. Bei der Aktion ist allerdings dieser PR geschlossen worden.

Das nur zur Info. :(

2023-02-08 17:16 UTC, capoaira commented
Oh, ich hoffe, die Probleme halten nicht so lange an. Eigentlich sollte bei Git nichts dabei kaputtgehen. Komisch.
Da diese PR aber schon fast ein Jahr auf ist, war das Schließen wohl so oder so überfällig.

2023-02-08 19:49 UTC, 2Abendsegler commented
Die Branchs collector und master sind defekt. Wenn ich diesen Link https://raw.githubusercontent.com/2Abendsegler/GClh/collector/gc_little_helper_II.user.js anwähle, dann sind die letzten Änderungen nicht enthalten. Ich habe die Branchs schon gelöscht und anschließend aus einer anderen Branch wieder aufgebaut, ändert aber nichts. Wenn ich mit anderen Branch Namen arbeite, dann klappt alles wie gewohnt. Ich kann die Defekten sogar umbenennen und dann klappt es auch. Auffällig ist nur, dass nach dem Umbenennen der vorherige Name noch unter dem Link erreichbar ist. Scheinbar werden die nicht sofort gelöscht. Ich werde jetzt den collector nochmal löschen und dann mal 24 warten und nachsehen, ob er dann weg ist.
Mehr fällt mir nicht mehr ein. :(

2023-02-08 19:55 UTC, 2Abendsegler commented
Ach ja, der collector ist nach dem Löschen unter dem Link noch erreichbar, eine Kopie des collectors unter dem Namen collector2 hingegen nicht.