[Certitude] Show compact solution information
2Abendsegler/GClh pull request #2129
Opened 2022-05-19 14:36 UTC by ChristianGK-GC

- creates a box with all relevant information from Certitude
- offers a "Copy to clipboard" button

2022-05-19 16:07 UTC, 2Abendsegler requested changes
Du bist ja ganz schön fleißig. 😊

Ich hab mir deine Erweiterung noch nicht auf einer Certitute Seite angesehen. Ich bin nur mal durchs Coding gegangen. Sieht aus meiner Sicht soweit ok aus. Nur ein paar Kleinigkeiten vorab bevor wir anfangen zu testen.

- Hast du vielleicht ein paar Beispiele zu Certitute Seiten, mal mit und ohne Information und mal mit und ohne Spoiler?
- Kannst du vielleicht ein gutes Beispiel, gegebenenfalls mit abgeänderten Koordinaten ..., als Screenshot im Pull Request einfügen? Das könnten wir dann auch vielleicht fürs Changelog verwenden.
- Kannst du bitte das neue Certitude Kapitel weiter oben im Coding nach dem PGC Kapitel anordnen? Wir haben alle "kleinen" Seiten aus unerfindlichen Gründen oben aufgebaut, deshalb wäre es schön wenn das für diese Seite auch so wäre.  
- Ich frage mich gerade ob es immer Koordinaten geben muss? Womöglich muss man das prüfen.
- Kann es vielleicht auch sein dass die Koordinaten nicht die Final Koordinaten sind, sondern beispielsweise die Koordinaten für eine erste Station oder so? Ich habe nicht so besonders viel Erfahrung mit Certitude. Vielleicht müssen wir dann eine allgemeinere Bezeichnung verwenden.
- Ich finde wir sollten hier einen Parameter im Config vorsehen, mit dem man diese Erweiterung auch ausschalten kann. Das auch für den Fall, dass wir die Certitude Seite mit unserer Erweiterung behindern. Dann müssen wir nicht so schnell mit einem Fix reagieren. Standardmäßig könnte der Parameter eingeschaltet sein. Config Kapitel "Others" wäre wohl sinnvoll. Was meinst du?

@capoaira
Fällt dir noch was ein?

2022-05-19 21:17 UTC, ChristianGK-GC commented
Nach einigen Experimenten habe ich noch eine kleine Änderung vorgenommen.
Es müssen nicht zwangsläufig Final Koordinaten angegeben werden.
Sind es Koordinaten, dann ist es das Final.
Ich hab selbst mal einen Checker angelegt.
https://www.certitudes.org/certitude?wp=GC8J1H9
Certitude: gclh

2022-05-19 21:18 UTC, ChristianGK-GC commented
Habe noch 3 Screenshots hinzugefügt.
Kann kann gern noch welche unmasked machen.

2022-05-19 22:18 UTC, ChristianGK-GC commented
Hab nun auch den config Teil eingebaut.

2022-05-20 06:37 UTC, 2Abendsegler reviewed
Das sieht soweit alles prima aus, auch der Einbau des Parameters ist fast ok, hast dir viel Arbeit gemacht. Auch wenn du bis vor 2 Wochen noch keine Ahnung von JS hattest, sieht es so aus als hättest du dann durchaus Erfahrungen in anderen Sprachen.

Als ich deine Kommentare gelesen habe ist mir erst bewusst geworden, dass Beispiele zum Testen ja nur eingeschränkt Sinn machen, weil es ja eben um die Lösungsseite geht. Ich müsste also die Lösung erst erarbeiten oder du müsstest mir die Lösung verraten. Das wiederum bringt ein Problem zu Tage. Wir haben keinen freien Zugriff auf die Seite auf der wir Änderungen machen. Wenn es Probleme gibt, können wir gar nicht ohne weiteres tätig werden. Wir müssten uns zuerst Zugriff auf die Seite verschaffen. Mein Versäumnis, das hätte ich gleich bedenken müssen. 

Diese Vorstellung behagt mir nicht wirklich. Das bringt uns zu sehr unter Druck. Ich weiß gerade nicht ob wir die Erweiterung machen sollten.

@capoaira
Was meinst du?

---
Noch ein paar formale Dinge, Ideen und Vorschläge für die Zukunft, auch wenn einige davon Geschmackssache sind, es vielfach kein richtig und falsch gibt und es auch davon abweichende Lösungen geben kann. Bitte verstehe mich nicht falsch, ich will nicht meckern, deine Arbeiten sind völlig in Ordnung. Und häufig ändern wir insbesondere formale Dinge in einem kurzen Nachgang selbst ab.
(Bitte keine weiteren Änderungen an deiner Erweiterung machen bis wir beratschlagt haben, ob wir sie überhaupt übernehmen.)

- Du musst dich nicht überall und sofort einarbeiten. Wir können da auch aushelfen und Teile übernehmen, wie beispielsweise den Einbau des Parameters. Es fällt ja oft viel leichter sich einzuarbeiten und zu sehen worauf man vielleicht noch achten sollte, wenn man ein eigenes Beispiel hat.
- Zu deinem Parameter:
  - Neue Parameter werden farblich als neu gekennzeichnet mit Angabe der Version mit der sie eingeführt wurden.
  - Dein Parameter klappt beim Zuklappen des Kapitels Others nicht mit ein.
  - Unter dem Kapitel Others stehen sowieso Parameter zu den unterschiedlichsten Themen. Eine weitere Überschrift zu einem einzelnen Parameter würde ich eher nicht vorsehen.
- Wir versuchen unsere Erweiterungen eher unauffällig und wenn möglich im Stil der Seite durchzuführen. Insofern ist deine Schrift passend. Auf der rechten Seite befinden sich bereits Boxen in blau unterlegt und in blau eingerahmt. Und es gibt auch bereits Buttons in diesen Boxen. Das Aussehen deiner Box und deines Buttons ist ganz anders, durchaus ansprechend, aber eben anders.   
- Es kann besser sein, zuerst ein Issue aufzumachen, und eine mögliche Erweiterung zur Diskussion zu stellen, insbesondere bei etwas ganz Neuem wie hier, oder bei größeren Erweiterungen. Man kann die Erweiterung ja dann gegebenenfalls trotzdem selbst durchführen und diesen Wunsch auch schon im Issue benennen. Wir haben bereits ein paar fertige Erweiterungen aus den unterschiedlichsten Gründen nicht übernommen. 
- Das Verzeichnis zu den Screenshots und das Changelog bauen wir für gewöhnlich erst kurz vor einer neuen Version auf. Die dazu nötigen Informationen sollten wenn möglich in den Kommentaren im Issue bzw. im Pull Request hinterlegt werden. Bei deiner vorangegangenen Erweiterung mit den Clipboard Buttons in den Logs hatte ich einen Screenshot zu diesem Zweck im Kommentar deines Pull Requests eingefügt. Als ich um einen Screenshot bat meinte ich auch genau das, ich hatte mich aber unklar ausgedrückt und du hast nur mitgedacht.
- Fürs Changelog wäre es vermutlich besser wenn wir Screenshots verwenden die nicht so sehr geschwärzt sind, du hattest es ja auch bereits angeboten.

2022-05-20 06:47 UTC, ChristianGK-GC commented
Du kannst gern einen Test mit folgendem Checker fahren:
https://www.certitudes.org/certitude?wp=GC8J1H9
Certitude: gclh

2022-05-20 06:49 UTC, 2Abendsegler commented
Danke für die Info.
Hatte ich schon gemacht.

2022-05-21 11:51 UTC, capoaira commented
Moin,
für zwei Wochen Erfahrung sieht das Coding aber sehr clean aus. Das war bei mir ganz anders 😅

>Wir haben keinen freien Zugriff auf die Seite auf der wir Änderungen machen. Wenn es Probleme gibt, können wir gar nicht ohne weiteres tätig werden. Wir müssten uns zuerst Zugriff auf die Seite verschaffen. Mein Versäumnis, das hätte ich gleich bedenken müssen.
>
> Diese Vorstellung behagt mir nicht wirklich. Das bringt uns zu sehr unter Druck. Ich weiß gerade nicht ob wir die Erweiterung machen sollten.
> 
> @capoaira Was meinst du

Wir haben ja den Test Checker und könnten so jederzeit auf der Seite Anpassungen vornehmen. Das geht in meinen Augen fast noch einfacher, als für BM Sachen zu testen. 😅

Allerdings sehe ich keinen Mehrwert in diesem Feature, da es einen Button `'Personal Cache Note' übernehmen` gibt, mit dem Certitude alle wichtigen Informationen in die Personal Notes lädt, und die Koords anpasst.
Hier stelle ich also mal die Frage, die mir @2Abendsegler, so oder so ähnlich, auch schon ein paar mal stellen musste: Wofür wird diese Funktion eigentlich benötigt?
Ich habe hier auch schon das Ein oder Andere mal Funktionen entwickelt, einfach, weil ich es konnte, Spaß dran hatte und wir was Ähnliches hatten, zudem es gepasst hätte. Doch wirklich danach gefragt hat keiner. Ein junges Beispiel ist #2112 
Sei also bitte nicht enttäuscht, falls wir das hier nicht übernehmen.
Vielleicht hast du aber auch einen guten Grund, den ich einfach nicht sehe.

Die Funktion an sich betrachtet funktioniert super und ohne Probleme. Wenn wir das übernehmen, habe ich dieselben Punkte wie @2Abendsegler

2022-05-21 21:08 UTC, 2Abendsegler commented
Äh, was ist BM noch mal? 🙄

2022-05-21 23:27 UTC, capoaira commented
Basic Member, in diesem Fall zumindest, könnte auch Bookmark bedeuten 😅 - vielleicht sollte ich das mit den Abkürzungen lassen 🤣

2022-05-22 06:09 UTC, 2Abendsegler commented
Ja genau, ich stand nur auf dem Schlauch. Abkürzungen sind prima. Schönen Sonntag.

2022-05-22 09:01 UTC, ChristianGK-GC commented
Hallo ihr beiden,

vielleicht etwas Kontext zu meinem Problem/Idee/Code.
Die Funktion `'Personal Cache Note' übernehmen` ist mir bekannt, jedoch hat sie einen gravierenden Haken. Spoiler werden nicht mit übernommen.
Dazu kommt noch die Tatsache, dass ich gern Notizen in GSAK hinterlege und diese von GSAK zur `Personal Cache Note` hinzufügen lasse.
Die Gedanken zum Style verstehe ich und ist ok für mich. Ich wollte so ne Art "Post-It" bauen.
Wie ihr euch auch immer entscheidet der Code ist nicht umsonst. Solltet ihr es nicht einbauen wollen, verstehe ich das und werde den in ein eigenes Script auslagern.
Außerdem hat es Spaß gemacht ;-)

2022-05-22 09:37 UTC, capoaira commented
> Spoiler werden nicht mit übernommen

Das war mir nicht bewust. In dem Beispiel scheint es kein Spoiler zu geben. Könntest du noch einen hinzufügen? 

Von GSAK habe ich keine Ahnung. In der Hinsicht kann ich das also nicht beurteilen.

2022-05-22 11:37 UTC, ChristianGK-GC commented
Habe noch ein Spoiler hinzugefügt.
GSAK ist nur ein Beispiel. Man könnte es auch sonst wo hin kopieren wollen.
Kannst es testen wenn du magst.

https://www.certitudes.org/certitude?wp=GC8J1H9
Certitude: gclh

2022-05-24 21:27 UTC, 2Abendsegler requested changes
_Ich habe mit das Ganze nochmal angesehen:_
Certitude kann nur dann das Ergebnis in die Personal Cache Note übernehmen, wenn man auch angeloggt ist. Ich bin nie angeloggt. Dabei wird eine bestehende Personal Cache Note überschrieben. Und der Spoiler wird gar nicht von Certitude übernommen. Die Erweiterung macht das also schon etwas flexibler. 
So wie capoaira schon geschrieben hat, behebt das Test Certitude auch meine zuvor geäußerten Bedenken.

_Ich würde nun doch die Erweiterung übernehmen wollen._ @capoaira, ok?

_Folgende Anpassungen sollten aus meiner Sicht noch gemacht werden:_
(Den ersten Punkt könnte ich im Anschluss an die Änderungen von ChristianGK-GC übernehmen.)
1. Parameter korrigieren.
2. Das Ganze in eine blaue Box packen so wie die anderen blauen Boxen auf der Seite. Und den Button so gestalten wie die anderen auf der Seite. Die neue blaue Box rechts unter die erste blaue Box von Certitude schieben oder an der jetzigen Stelle belassen, dann aber oberhalb des Werbebanners. Werbeblocker mal deaktivieren, dann sieht man das. 
3. Falls die "Post it" Box noch gewünscht ist, die Idee finde ich gar nicht schecht, kann man die in einem zweiten Rahmen innerhalb der blaue Box anbringen, so oder so wie du möchtest.
4. Wenn es nach dem Doppelpunkt von Final und von Spoiler in der gleichen Zeile weiter geht, sollte es das auch bei Info, finde ich.
5. Das Test Certitude sollte erhalten bleiben und an entsprechender Stelle im Coding Erwähnung finden.
6. Fürs Changelog einen Screenshot mit echten Werten anzeigen, am Besten das Test Beispiel. Restliche Screenshots entfernen.
7. Mit dem Spoiler Link wird der Seiteninhalt ziemlich nach rechts gedrückt. Der Link darf nicht die Breite der Box bestimmen. Der Link muss vorher umbrechen. 
![grafik](https://user-images.githubusercontent.com/22332216/170134484-f8921730-f213-4fa9-acce-f1aeb6d43d68.png)

2022-05-25 02:07 UTC, ChristianGK-GC commented
Ich habe das Style jetzt an die Seite angepasst. Sollte nun so passen.
Die Schicht habe ich Linksbündig gemacht, weil es zentriert sehr unübersichtlich ist.

Die Box habe ich über die existierenden Blauen gepackt. Ich Fand es besser.
Wenn ihr darauf besteht, dann pack ich es aber gern auch unter die erste Box.

Der Rest sollte nun auch passen.

2022-05-30 20:42 UTC, capoaira reviewed
Moin,
tut mir leid, dass es so lange dauert, bis hier jemand antwortet. Momentan habe ich vieles andere um die Ohren, und 2Abendsegler scheinbar auch.

Das Styling sieht soweit gut aus. Ich habe drei Bemerkungen im Code hinzugefügt, wie es IMO besser wäre. (Ist natürlich etwas Geschmackssache)

>Die Box habe ich über die existierenden Blauen gepackt. Ich Fand es besser.
>Wenn ihr darauf besteht, dann pack ich es aber gern auch unter die erste Box.

Ich denke, und auch das ist rein subjektiv, dass viele den Button `'Personal Cache Note' übernehmen` bevorzugen. Zumindest tue ich das. Mir wurde dieses Feature in der Mitte der beiden existierenden Kästen am besten gefallen. @2Abendsegler, was meinst du?

@ChristianGK-GC: Warte am besten noch auf 2Abendseglers Antwort, bevor du weitere Änderungen vornimmst.

2022-05-30 20:42 UTC, capoaira commented on gc_little_helper_II.user.js
> +                var output = '<div>';
Hier bitte ein `<div id="inputArea">` einfügen, um zum restlichem code konsistent zu sein.
(Ja, ids mehrfach zu vergeben ist eine Unart, aber hierdurch wird das Styling bestimmt, und deshalb sollten auch wir das so machen, falls etwas am Styling verändert wird, wird es automatisch übernommen.

2022-05-30 20:42 UTC, capoaira commented on gc_little_helper_II.user.js
> +                output += '<div id="gclh_solution" style="padding: 2px 10px; background-color: #d7e5f5; border: solid 1px #85b1de;  text-align: left;">';
Hier kannst du den style entfernen. (s.o.)

Ich bin kein Fan von dem Linksbündigen, da ausnahmslos alles andere zentriert ist.

2022-06-05 22:44 UTC, ChristianGK-GC commented
Kann das gern umsetzen, auch wenn ich kein Großer Fan von zentriert bin ;-)
Bzgl der Position unter der `'Personal Cache Note'` find ich auch besser.

2022-06-08 09:10 UTC, 2Abendsegler commented
@capoaira, alles gute Punkte, kann ich überall zustimmen. Die Vorschläge zu den Anpassungen im Coding finde ich sehr gut, wieder klasse mitgedacht, an mir wäre das sicherlich vorbei gegangen. 
@ChristianGK-GC, bitte baue die Punkte noch ein.
Ich fände einen zentrierten Inhalt, inklusive Button, passender, weil es auf der Seite ausnahmslos so ist und damit einheitlicher wird.

---
Off Topic: Sorry, dass es so lange dauert. Die nächsten Tage sollte ich wieder mehr Zeit haben. Gegen Ende der Woche werde ich versuchen eine neue Version zu erzeugen, sofern ich meine beiden Bugs bis dahin geregelt habe.

2022-06-09 21:32 UTC, ChristianGK-GC commented
Hallo ihr beiden,

ich bin zZ im Urlaub ich erst nächste wieder im Lande.
Werde dann auch erst dazu kommen etwas zu ändern.

Gruß
Christian

2022-06-10 10:28 UTC, capoaira commented
Ok, kein Problem.

Ich wünsche dir einen schönen und erholsamen Urlaub 😊

2022-06-10 22:54 UTC, ChristianGK-GC commented
Tach zusammen,
ich hatte heute nichts besseres zu tun und hab das mal so eingebaut.
Bin gespannt was ihr dazu sagt.
So ein Regentag kann auch etwas positives haben 😅

2022-06-12 09:34 UTC, 2Abendsegler approved these changes
Sieht prima aus, danke!

---
Ich werde die Anpassungen im Anschluss mergen und dann noch den Parameter vollständig integrieren und vielleicht noch ein paar Kleinigkeiten ändern.

2022-06-12 09:35 UTC, merged