Show cache/TB type in front of log type in Latest Activity list
2Abendsegler/GClh pull request #2165
Opened 2022-07-18 10:33 UTC by 2Abendsegler

Upload js
#2164

@capoaira 
Kannst du dir das bitte bei Gelegenheit ansehen.

2022-07-18 10:47 UTC, capoaira requested changes
Sieht erstmal gut aus. Mir ist aber eine Kleinigkeit aufgefallen:
Wenn ich auf einen Logeintrag klicke, ihn also aufklappe, wird das Icon entfernt und unten eingefügt. Wenn man den Log dann wieder einklappt, fehlt das Type-Icon komplett.

Ich habe momentan eine TB Activity bei mir, die funktioniert so weit auch ;)

Es wäre meiner Meinung nach auch schön, wenn es auch funktionieren würde, falls man den Tab wechselt, bzw. ihn ein und wieder ausklappt. Ich kann aber gerade nicht einschätzen, wie viel zusätzliche Arbeit das macht...

2022-07-18 11:02 UTC, 2Abendsegler commented
Mal wieder super schnell. 😊 Danke für dein Feedback. 👍

Gut aufgepasst mit der "Kleinigkeit", war mir entgangen. Das werde ich auf jeden fall noch korrigieren. (Icon steht immer unten. Ich habe es nur zusätzlich nach oben geholt.)

> Es wäre meiner Meinung nach auch schön, wenn es auch funktionieren würde, falls man den Tab wechselt, bzw. ihn ein und wieder ausklappt. Ich kann aber gerade nicht einschätzen, wie viel zusätzliche Arbeit das macht...

Ja, du hast recht. Ich werde versuchen beides noch einzubauen.

2022-07-18 12:13 UTC, 2Abendsegler commented
@capoaira 
Es sollte nun alles funktionieren. Kannst du bitte noch mal testen.
Das Feature mit dem Edit Button musste angepasst werden, um das neue Feature dort zu integrieren.

---
> Icon steht immer unten. Ich habe es nur zusätzlich nach oben geholt.

Stimmt ja gar nicht, auch hier hattest du völlig recht. Ich habs ja gar nicht geclont. Das nur nebenbei.

2022-07-18 12:45 UTC, capoaira commented on gc_little_helper_II.user.js
> +            html += checkboxy('settings_show_cache_type_icons_in_dashboard', 'Show cache/TB type in front of log type in Latest Activity list') + "<br>";
Oh, was mir gerade noch auffällt, wir sind schon bei Version 0.11 ;)

2022-07-18 12:54 UTC, 2Abendsegler commented
> Bei `Community` und `Your Hides` funktioniert es jetzt jedoch gar nicht mehr :(

Das kann ich gerade nicht nachvollziehen. Ich habe gerade keine Hides aber mit Community funktioniert bei mir alles. Ich habe gerade auch keine Idee, woran das hängen könnte.
Kannst du bitte mal die Console auf Fehler prüfen?
Und kannst du bitte mal prüfen ob der Edit Button auch bei Community vorhanden ist?

2022-07-18 13:18 UTC, 2Abendsegler commented
> Dann teste ich heute Abend nochmal ausführlicher

Danke dir.

Habe noch ein Commit gemacht:
- Version im Config wird jetzt richtig gesetzt.
- More Button wird nun auch in der neuen Function zusätzlich aufgebaut.

2022-07-19 12:52 UTC, capoaira commented
Ich habe nochmal geguckt, bei eigenen Logs funktioniert das in jedem Tab (ich musste dafür im Moment sehr weit runterscrollen 😅)
Bei den Logs von anderen wird der Cachetyp nicht angezeigt. Einen Fehler in der Console gibt es nicht.
Vermutlich werden Logs von anderen aufgrund der Implementierung des Edit Links nicht beachtet. (Für den Link konnte man ja

2022-07-19 13:03 UTC, 2Abendsegler commented
Danke. 
Hört sich plausibel an. Ich werde mir das mal mit Logs von Anderen ansehen. Gibt es im Moment zwar nicht, aber vielleicht erzeuge ich mir welche mit einer Sockenpuppe.

2022-07-19 13:07 UTC, 2Abendsegler commented
Hihi, sehr schön! 😊

2022-07-19 13:42 UTC, 2Abendsegler commented
Du hattest recht!
Das Problem ist gefixed.
Kannst du bitte bei Gelegenheit noch mal drüber schauen.

2022-07-19 17:36 UTC, merged

2022-07-19 17:39 UTC, 2Abendsegler commented
Danke für deine Unterstützung. :)