Show log text in Markdown as it is in cache listing
2Abendsegler/GClh pull request #2224
Opened 2022-10-09 05:53 UTC by 2Abendsegler

#2223

2022-10-09 05:55 UTC, 2Abendsegler commented
@capoaira 
Moin,
kannst du dir das bitte bei Gelegenheit mal ansehen.
Danke.

2022-10-09 14:04 UTC, capoaira requested changes
Moin,
die kleine Vorschau wird durch die Funktion verändert, hier sollte das in einer Reihe bleiben
Mit: 
![grafik](https://user-images.githubusercontent.com/50927164/194760696-11d02d9f-4564-43fd-ab47-7f301163da0e.png)
Ohne:
![grafik](https://user-images.githubusercontent.com/50927164/194760656-43c6b68a-333c-45af-8cd8-5ceb551c9668.png)

2022-10-09 18:30 UTC, 2Abendsegler commented
Hm, das entsprechende Log sieht aber so aus
![grafik](https://user-images.githubusercontent.com/22332216/194771569-87b791ea-a33d-4150-a240-ec775fc12a9a.png)

Von GS wird halt nichts aufbereitet und es steht alles hintereinander. Wenn die kleine Vorschau nicht aufbereitet wird, dann könnte es auch beispielsweise so aussehen 
`**Found 3700** *09.10.2022* [GC little helper II - Some little things to make life easy (on www.geoc`
was auch blöd wäre.

Wir könnten für die kleine Vorschau einen weiteren Parameter einbauen über den dann gesteuert wird, ob auch dort umgewandelt wird. Was meinst du?

2022-10-10 08:23 UTC, capoaira commented
Ich denke in der Vorschau geht es darum so viel vom Log wie möglich zu zeigen. Dann sieht man, ob es sich "lohnt" den Log zu lesen. Daher denke ich, dass es Sinn macht, die Vorschau so zu lassen wie sie ist (und evtl. nur die Smileys schön zu machen)
Wenn man dann den Log anklickt, sieht man den schön formatierten Log.
Ist aber natürlich nur meine Meinung, deinen Gedanken kann ich auch nachvollziehen. 

Ein weiterer Parameter macht das ganze, denke ich, zu kompliziert. Wir sollten uns für eines entscheiden.

2022-10-11 13:16 UTC, 2Abendsegler commented
@capoaira 
Wir belassen die einzeilige Vorschau dann so wie sie im Original ist. Markdown gibt es nur bei der Anzeige des Logs.
An den Smileys bei der einzeiligen Vorschau habe ich nichts verbessert.

Kannst du bitte bei Gelegenheit noch mal drüber schauen.

2022-10-11 13:51 UTC, capoaira approved these changes
Sieht super aus 👍🏻

2022-10-11 13:51 UTC, merged