[COD] Link to CCE are undefined
2Abendsegler/GClh pull request #2248
Opened 2022-12-17 14:35 UTC by capoaira

2022-12-23 19:29 UTC, 2Abendsegler requested changes
Moin,

ich kann das selbst nicht testen. Es sieht so aus als ob du nur den Namen für ein CCE geändert hast, oder?

Ich weiß nicht wo wir die Namen hernehmen. Wenn ich mir im Profil die Caches ansehe dann steht dort für ein CCE "Community Celebration Event". "Cache" steht dort nicht. 
![Zwischenablage01](https://user-images.githubusercontent.com/22332216/209397507-f8fb09f6-a444-437a-95af-a439d8940ee7.jpg)

Wenn wir "Cache" beim CCE dranhängen, was wir durchaus machen können, dann sollten wir aber vielleicht beim CITO ebenfalls "Cache" dranhängen, oder? Dann würde "Cache" überall stehen.

2022-12-23 22:24 UTC, capoaira commented
Moin,
die Liste selber wird von GS erstellt, wir fügen ja nur die Links hinzu. Den Typen nehme ich aus einem Attribut des Listeneintrags. Wir haben alle Typen die wir testen konnten getestet (Ruko2010 hat auch ein CITO, also wurde das auch getestet). Tatsächlich gleichen alle Namen denen aus dem Profil, aber bei CCEs hat sich GS scheinbar nicht an ihr Muster gehalten. Das ist mir erst jetzt aufgefallen, wo ich selber ein CCE habe.
Also wenn GS sonst nichts geändert hat, sollten wir beim CITO nichts ändern.

2022-12-23 22:25 UTC, capoaira commented
Also dieser PR ändert nichts, was angezeigt wird, sonder nur, wie ein Cachetyp erkannt wird.

2022-12-24 00:28 UTC, 2Abendsegler approved these changes

2022-12-24 00:31 UTC, merged

2022-12-24 08:43 UTC, 2Abendsegler commented
Ok, super, hab mal wieder auf dem Schlauch gestanden. 🤭 
Danke für die Rückmeldung und frohe Weihnachten!

---
Das hatte ich gestern schon im merged commit hinterlegt, was aber in der Conversation zum PR gar nicht auftaucht.