Add county to cache information
2Abendsegler/GClh pull request #2423
Opened 2023-10-29 17:38 UTC by capoaira

#2419

2023-10-29 18:15 UTC, 2Abendsegler reviewed
Moin,

super, du bist ja richtig fleißig. 😊
Ich bin nur gerade mal kurz drüber geflogen, sieht schon mal gut aus, hatte aber noch keine Zeit zu testen.

Es sind mir noch zwei Dinge aufgefallen:

1. Vielleicht könnten wir das Fetch ... auch in einen try-catch Block legen?

2. Vielleicht könnten wir die Funktionalität auch auf den beiden Karten in der Detailanzeige zum Cache, also im Popup bei der Browse Map und links in der Detailanzeige in der Search Map vorsehen? Das war im [Beitrag im Forum](https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/&do=findComment&comment=6104165) ja auch gewünscht und macht meines Erachtens auch ziemlich Sinn.
Wir müssen die Karten dann hier nicht unbedingt gleich mit abhandeln, wir könnten auch ein oder zwei neue Issues dazu aufmachen. 
Vielleicht sollten wir die Funktionalität schon mal kapseln, damit wir sie auch aus den Karten aufrufen können?

Was meinst du?

2023-11-02 18:29 UTC, capoaira commented
Gute Idee, ich habe die Funktion gekapselt und den Parameter umbenannt

2023-11-03 22:44 UTC, 2Abendsegler requested changes
@capoaira 
Moin
Ich habe nur einen kleinen Punkt, der hier nicht korrekt läuft:
Bei Caches aus Hamburg wird kein "state" mitgeliefert. Das könnte ein Fehler in den openstreetmap Daten sein. Wir sollten also prüfen, ob "state" vorhanden ist, bevor wir es verwenden bzw. bevor wir überhaupt Daten im Listing ändern. Beispiel: https://coord.info/GC4T7NH

---
Ich finde die Übersetzungen manchmal etwas unglücklich und weiß nicht so recht ob wir überhaupt übersetzen sollten. Ich habe aber keine bessere Vorgehensweise gefunden als die, die du entwickelt hast. 

Die folgenden Infos habe ich nur der Vollständigkeit halber angefügt, damit ich sie mir nicht nochmal zusammen suchen muss, falls ich sie nochmal brauche.

Infos zu den automatischen Übersetzungen:
Bei GS werden wohl die Bundesländer nicht übersetzt, auch wenn ich in Englisch oder Tschechisch angemeldet bin, stehen sie dort in der Sprache des entsprechenden Landes. Die Landesnamen werden bei GS immer in Englisch angezeigt. 
Wir übersetzen nun alles mit der angemeldeten Sprache entsprechend den Angaben bei openstreetmap. Damit werden auch beispielsweise Städtenamen und Bundesländer übersetzt. GC7YRJN "Dresden, Sachsen, Germany" heißt in tscheschich angemeldet dann "Drážďany, Sasko, Německo". GC8NA1H "Bremen, Bremen, Germany" wird in englisch angemeldet dann zu "Bremen, Free Hanseatic City of Bremen, Germany" und in tscheschich zu "Brémy, Svobodné hanzovní město Brémy, Německo".

2023-11-04 10:00 UTC, capoaira commented
Oh, ich bin davon ausgegangen, dass ein `state` immer verfügbar ist.
"Free Hanseatic City of Bremen" finde ich auch unglücklich lang, fand das aber noch akzeptabel.

Mein ursprünglicher Plan, war es, die county Information, sofern verfügbar, einfach vorne anzuhängen. Leider fand ich aufgrund des "In", was in anderen Sprachen mehr als ein Wort sein kann, keine Möglichkeit, wie ich das passend einfügen kann. Daher die Ersetzung des ganzen Inhaltes.

Das ist irgendwie alles etwas ungünstig. Ich hatte auch Probleme, die gekapselte Funktion in die Map einzubauen. Jetzt werde ich das aber denke ich so machen, wie bei `getFavoriteScore`

Ich lasse die PR aber erstmal als Draft, bis wir wissen, wie, bzw. ob wir das sinnvoll umsetzten können.

2023-11-04 10:40 UTC, 2Abendsegler commented
> Oh, ich bin davon ausgegangen, dass ein `state` immer verfügbar ist.

Ich denke das ist tatsächlich auch ein Fehler in openstreetmap, und ich bin auch nur durch Zufall darauf gestoßen, weil ich vergleichen wollte, ob auch bei Hamburg Hansestadt groß und breit übersetzt wird, wie bei Bremen.

> Ich hatte auch Probleme, die gekapselte Funktion in die Map einzubauen. Jetzt werde ich das aber denke ich so machen, wie bei `getFavoriteScore`

Dann gehe ich mal davon aus, dass du vor hast die Funktionalität über das aktuelle Issue auch in den Karten einzubauen, sehr schön. 😊

Bei den Karten ist noch zu beachten, dass wir dort die Möglichkeit geschaffen haben wegen des Platzmangels und des damit verbundenen Zeilenumbruchs (in der Browse Map) wahlweise nur state direkt anzuzeigen. state und country werden dann immer komplett im title angezeigt. [Parameter](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_country_in_place).

Vielleicht können wir das zusätzliche Feld auch wahlweise im title verschwinden lassen. Die gesamte Adresszeile, wie im title im Listing, würde ich in den Karten nicht vorsehen.

> Mein ursprünglicher Plan, war es, die county Information, sofern verfügbar, einfach vorne anzuhängen. Leider fand ich aufgrund des "In", was in anderen Sprachen mehr als ein Wort sein kann, keine Möglichkeit, wie ich das passend einfügen kann. Daher die Ersetzung des ganzen Inhaltes.

Ja, verstehe. Hast du mal bei Project-GC nachgeschaut wie die das machen?

Bei der Durchsicht der Karten ist mir aufgefallen, dass wir es dort schaffen, das "In" wegzulassen. Womöglich haben wir dort dann noch ein Problem und entfernen immer nur das erste Wort. Womöglich haben wir uns dort auch auf den Standpunkt gestellt, dass wir nur Englisch bedienen müssen.

2023-11-04 17:39 UTC, capoaira commented
> Bei der Durchsicht der Karten ist mir aufgefallen, dass wir es dort schaffen, das "In" wegzulassen. Womöglich haben wir dort dann noch ein Problem und entfernen immer nur das erste Wort. Womöglich haben wir uns dort auch auf den Standpunkt gestellt, dass wir nur Englisch bedienen müssen.

Jip, dort wird einfach nur das erste Wort weg gelassen.
```js
$(text).find('#ctl00_ContentBody_Location')[0].innerHTML.replace(/(.*?)\s/,'');
```
Ich würde sagen, wir berufen uns weiterhin darauf. Ich denke auch, dass die meisten Nutzer eine Sprache nutzen, wo diese Lösung reicht.


> Ja, verstehe. Hast du mal bei Project-GC nachgeschaut wie die das machen?

Die nutzen ihre eigene API: https://github.com/magma1447/greasemonkey-geocaching-projectgc/blob/43e286471992b6a2b61c8f365a752c59bb741eec/greasemonkey-geocaching-projectgc.user.js#L728



> Bei den Karten ist noch zu beachten, dass wir dort die Möglichkeit geschaffen haben wegen des Platzmangels und des damit verbundenen Zeilenumbruchs (in der Browse Map) wahlweise nur state direkt anzuzeigen. state und country werden dann immer komplett im title angezeigt. [Parameter](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_country_in_place).

Ok, ich werde darauf achten.

2023-11-04 20:01 UTC, capoaira commented
Hmm, so richtig zufrieden werde ich mit dem Service nicht. Bei GCAFKWP wird mir als City "Stadtgebiet Bremen" zurückgegeben, bei anderen nur "Bremen". Das finde ich sehr inkonsistent. Ich werde mich nach einem neuen Service umschauen...

2023-11-04 20:15 UTC, 2Abendsegler commented
Ja, das scheint wirklich nicht zufriedenstellend.

2023-11-04 20:45 UTC, closed without merging