F2 for new logging
2Abendsegler/GClh pull request #2437
Opened 2023-11-06 16:09 UTC by capoaira

#2424 

wird erst funktionieren, sobald #2435 gemerged ist

Entfernt auch alte Bookmark Links, die es nicht mehr gib.

Die Beschreibung im config muss auch noch angepasst werden.

(Ich erstelle die PR nur zur Übersicht)

2023-11-06 17:34 UTC, 2Abendsegler commented
Ich möchte dich nicht ausbremsen, aber du machst hier stellenweise Refactoring, Redesign ohne dass daraus ein echter Mehrwert entsteht. Ich bin tatsächlich kein Freund davon, ganz im Gegenteil. Durch solche Änderungen entsteht Aufwand, nicht nur beim Codieren selbst, sondern auch beim Testen. Und es birgt auch die Gefahr, dass Fehler eingebaut werden. 

Am Coding haben in den vielen Jahren viele Entwickler mitgewirkt. Jeder hat auf seine eigene Art und Weise entwickelt und es ist ein richtiges Durcheinander entstanden. Das ist ok so! 
Sobald wir die Entwicklungen getestet und approved haben, gibt es aus meiner Sicht keinen Grund mehr an dem Coding Änderungen vorzunehmen, es sei denn es funktioniert etwas nicht so gut oder nicht mehr oder es soll etwas Größeres dazu gebaut werden. Wenn Änderungen notwendig sind, dann machen wir das zeitlich direkt im Umfeld vom Testen und Approven. In der Regel sind wir aber sehr großzügig, was die jeweilige Art und Weise des Entwickelns angeht und winken auch Coding durch, das nicht unseren eigenen Vorstellungen entspricht.

Wenn du dir beispielsweise mein übliches Coding ansiehst, dann würdest du zu Recht alles mögliche ganz anders machen. Schon deshalb, weil deine Kenntnisse in JS und auch anderswo viel größer sind. 

Der Austausch von `id` durch `selector` fällt vermutlich in die Kategorie Schönmachen des Codings. Ein Mehrwert entsteht daraus nicht. Ich müsste aber alles mögliche durchtesten.

Das Löschen von `if (document.location.href.match(/\.com\/bookmarks\/mark\.aspx/)) var id = "ctl00_ContentBody_Bookmark_btnCreate";` wäre ein typischer Fall für einen eingebauten Fehler. Ich weiß das nur zufällig genau für diesen Punkt, weil ich dieses Feature immer noch nutze um einen Cache in eine BML zu hängen und gleichzeitig eine Notiz mitzugeben. Versuch mal rechte Maustaste auf `Add to List` im Cache Listing und dann `Link in neuem Tab öffnen`.

Mir wäre es lieber, wenn wir nicht ohne Not an bestehendem Coding Änderungen vornehmen. 😓

2023-11-06 19:14 UTC, 2Abendsegler commented
> Das Refactoring mit dem Selektor ist jedoch nötig, da der Button beim neuen Logformular keine id hat, sondern nur Klassen. Damit kann das alte Coding nicht umgehen, da es `document.getElementById()` nutzt. Durch das Refactoring war es einfacher, die neue Seite hinzuzufügen.

Ok, verstehe.

> Ich habe die PR erstellt, damit wir nicht versehentlich doppelt arbeiten.

Guter Punkt, werde ich auch machen.

2023-11-09 21:28 UTC, 2Abendsegler requested changes
Mir sind leider einige Punkte aufgefallen, wo wir anders vorgehen müssen. Leider scheint es doch nicht einfacher geworden zu sein im Redesign des neuen Log Formulars. 😓

1.) Die Verarbeitung zur Personal Cache Note funktioniert leider nicht mehr. Hier muss auch auf den selector umgestellt werden, ansonsten ist das bei function keydownF2 außen vor. 
Das betrifft folgendes Coding:
```
            function setButtonDescInnerHTMLF2(waitCount, id) {
                if (document.getElementById(id) && document.getElementById(id).innerHTML && !document.getElementById(id).innerHTML.match(/(F2)/)) {
                    document.getElementById(id).innerHTML += " (F2)";
                }
                if (waitCount <= 20) setTimeout(function(){setButtonDescInnerHTMLF2(waitCount, id);}, 100);
            }
```
```
            // "Save" personal cache note in cache listing.
            if (is_page("cache_listing") && $('.js-pcn-submit')[0]) {
                var id = "gclh_js-pcn-submit";
                $('.js-pcn-submit')[0].id = id;
                setButtonDescInnerHTMLF2(0, id);
            }
```

2.) Wenn ich im Log Formular die Konsole aufmache, die Seite im Browser aktualisiere, dann ist anschließend bei Post kein " (F2)" im Button zu sehen. Ich weiß, die Aktualisierung über den Browser ist jetzt keine typische Verarbeitung an dieser Stelle, trotzdem sollte auch das funktionieren. 

3.) Bei den Autovisits, Logtemplates, Signaturen ... mussten wir bisher beim neuen Log Formular immer prüfen und gegebenenfalls warten bis die Stelle zum Einfügen vorhanden ist. Teils mussten wir sogar mehrfach einfügen, weil Coding wieder verschwunden ist. Ich hatte die VIP, VUP und die Mail, Message Verarbeitungen abgespeckt und ohne solches Coding versehen und musste es überall wieder nachbauen.

Selbst bei den Additional Cache Info muss ich solches Coding jetzt dazu bauen, was bisher nicht der Fall war. Obwohl hier ja zuerst noch das Cache Listing nachgelesen werden muss, was ja Zeit in Anspruch nimmt, lief das nicht stabil.

Und der GClh Header verschwindet ja auch mal im Log Formular. (Issue #2443)

Offenbar läuft immer noch einiges asynchron oder wird sogar mehrfach geladen.

Vielleicht sollten wir überlegen, ob wir nicht einen Observer einbauen und alle einzelnen Themen so aufbauen, dass immer wieder erneut Coding eingebaut werden kann, falls es verschwindet. Wir könnten alles zusammen in eine function packen, die vom Observer aufgerufen wird. Der derzeitige Aufbau ändert sich dann nur vorne und hinten im neuen Bereich für das Log Formular.

Das F2 Thema für den Post Button sollte dann vielleicht auch dort angesiedelt werden. Der F2, F4 ... Coding Bereich könnte dann auch so bleiben wie er ist. Es hat sich schon lange gezeigt, dass das gewaltsame Zusammenpacken vielfach unglücklich ist.

Oder hast du andere Vorschläge?
Was denkst du?

2023-11-10 07:21 UTC, capoaira commented
1. Werde ich anpassen. Da war ich wohl schlampig beim testen :(

2. Kann ich leider nicht reproduzieren. Bei mir funktioniert auch mit geöffneter Konsole. (Firefox, Chrome)
Allerdings ist mir bei der Signatur aufgefallen, dass in Chome der Date Input verspätet geladen wird. Dabei ist wurde auch das Logfeld leer geräumt.

Diese Funktion habe ich nur in Firefox getestet. 
Welchen Browser nutzt du?
Evt reicht es immer auf den Date input zu warten. Dies habe ich für die Signatur aber auch noch nicht für alle Logtypen getestet...

2023-11-10 08:15 UTC, capoaira commented
> Vielleicht sollten wir überlegen, ob wir nicht einen Observer einbauen und alle einzelnen Themen so aufbauen, dass immer wieder erneut Coding eingebaut werden kann, falls es verschwindet. Wir könnten alles zusammen in eine function packen, die vom Observer aufgerufen wird. Der derzeitige Aufbau ändert sich dann nur vorne und hinten im neuen Bereich für das Log Formular.

Das könnten wir auch machen. Bei der Karte und den BMLs hat sich das ja bewährt.



> Das F2 Thema für den Post Button sollte dann vielleicht auch dort angesiedelt werden. Der F2, F4 ... Coding Bereich könnte dann auch so bleiben wie er ist. Es hat sich schon lange gezeigt, dass das gewaltsame Zusammenpacken vielfach unglücklich ist.

Ja und Nein. Eigentlich ist es wichtig alles zusammenzupacken, was zusammen gehört, doch GS nutzt so verschiedene Techniken über die Seiten hinweg, sodass es nur schwer möglich ist.

2023-11-10 13:02 UTC, 2Abendsegler commented
> Welchen Browser nutzt du?

Auch Firefox. Unter Windows 10. 

> > Vielleicht sollten wir überlegen, ob wir nicht einen Observer einbauen und alle einzelnen Themen so aufbauen, dass immer wieder erneut Coding eingebaut werden kann, falls es verschwindet. Wir könnten alles zusammen in eine function packen, die vom Observer aufgerufen wird. Der derzeitige Aufbau ändert sich dann nur vorne und hinten im neuen Bereich für das Log Formular.
> 
> Das könnten wir auch machen. Bei der Karte und den BMLs hat sich das ja bewährt.

Ja, stimmt, das hat sich bewährt. Auch deshalb würde ich das bevorzugen. Damit wären wir auf der sichereren Seite und dann können die Daten kommen wann immer sie wollen. 
Kannst du den Observer einbauen und den Bereich Log Formular entsprechend organisieren? 

> > Das F2 Thema für den Post Button sollte dann vielleicht auch dort angesiedelt werden. Der F2, F4 ... Coding Bereich könnte dann auch so bleiben wie er ist. Es hat sich schon lange gezeigt, dass das gewaltsame Zusammenpacken vielfach unglücklich ist.
> 
> Ja und Nein. Eigentlich ist es wichtig alles zusammenzupacken, was zusammen gehört, doch GS nutzt so verschiedene Techniken über die Seiten hinweg, sodass es nur schwer möglich ist.

Ja, stimmt. 
Wenn wir den Observer nutzen, sollten wir auch das F2 Thema zum Log Formular dort abwickeln. Im F2, F4 ... Coding Bereich können wir das dann vermerken, dann ist doch auch gut. Wenn du die Umstellungen mit dem "selector" behalten möchtest, ist das ok, dann halt noch die Anpassungen mit der Personal Cache Note machen. Aus meiner Sicht können wir dort aber auch zurück. Machs wie du möchtest.

---
Off-Topic:
Hast du einen Paypal Account? Kannst du mir sagen wie ich ihn ansprechen kann, vielleicht über GC Message Center?

2023-11-12 13:36 UTC, capoaira commented
> Ja, stimmt, das hat sich bewährt. Auch deshalb würde ich das bevorzugen. Damit wären wir auf der sichereren Seite und dann können die Daten kommen wann immer sie wollen.
> Kannst du den Observer einbauen und den Bereich Log Formular entsprechend organisieren?

Jip, kann ich machen. Allerdings muss ich jetzt erstmal arbeiten und dann etwas für die Uni machen.


> Wenn wir den Observer nutzen, sollten wir auch das F2 Thema zum Log Formular dort abwickeln. Im F2, F4 ... Coding Bereich können wir das dann vermerken, dann ist doch auch gut. Wenn du die Umstellungen mit dem "selector" behalten möchtest, ist das ok, dann halt noch die Anpassungen mit der Personal Cache Note machen. Aus meiner Sicht können wir dort aber auch zurück. Machs wie du möchtest.

Ja, das macht dann auf jeden Fall Sinn. Ich würde dann den alten Bereich nicht anfassen, dann müssen wir weniger testen 😅

2023-11-16 21:17 UTC, 2Abendsegler commented
Ein Observer scheint nicht notwendig. Das lässt sich auch alles ohne lösen. Bring aber bitte die F2 Anpassungen trotzdem in den Bereich fürs Redesign. Ich werde das dann noch anpassen, ich kann ja einen Fehler produzieren, wo das wieder verschwindet.

2023-11-18 14:26 UTC, 2Abendsegler reviewed
Sieht eigentlich ok aus.

Wenn ich die Konsole aufmache bekomme ich aber manchmal einen Fehler:
![Unbenannt](https://github.com/2Abendsegler/GClh/assets/22332216/2838f85b-612f-4265-bbc5-de1bb6414819)
Außerdem verschwinden bereits durchgeführte Anpassungen am Button wieder. 

Du kannst den Fehler ja nicht nachvollziehen. Ich schlage deshalb vor, dass ich den PR approve und anschließend entsprechende Anpassungen vornehme. Ist das ok?

2023-11-18 14:47 UTC, capoaira commented
> Du kannst den Fehler ja nicht nachvollziehen. Ich schlage deshalb vor, dass ich den PR approve und anschließend entsprechende Anpassungen vornehme. Ist das ok?

Ja, das macht Sinn.
Ich denke du kannst dann `waitForElementThenRun('#log-date', () => {` und die schißende Zeile entfernen. Das hatte ich eingebaut, da das verschwinden der Änderungen damit bei mir gefixed wurde. Die Funktion ist auch für die Fehlermeldung verantwortlich, da logdate scheinbar nicht innerhalb einer Sekunden auftaucht.

2023-11-18 15:01 UTC, merged