[Log Form] Show additional cache info.
2Abendsegler/GClh pull request #2445
Opened 2023-11-11 14:17 UTC by 2Abendsegler

#2424

2023-11-11 14:18 UTC, 2Abendsegler commented
@capoaira 
Moin nochmal,
das "Show additional cache info" Feature zum Redesign ist fertig.
Kannst du bitte testen? Danke. 😊

2023-11-12 13:26 UTC, capoaira requested changes
Sieht gut aus.

Ich habe nur eine Kleinigkeit: Ich finde die FPs nicht klar genug von den FP% getrennt: ![grafik](https://github.com/2Abendsegler/GClh/assets/50927164/e8ff81e8-d636-4fa3-ad55-57b4e625579f) Ein Trennstrich oder klammern würde es meiner Meinung nach übersichtlicher machen.

2023-11-12 16:14 UTC, 2Abendsegler commented
> Ein Trennstrich oder klammern würde es meiner Meinung nach übersichtlicher machen.

Habs in Klammern gesetzt, so wie wir es auch in der Search Map machen.

2023-11-12 16:24 UTC, capoaira approved these changes
Perfekt :)

2023-11-12 16:24 UTC, merged