Improve notification list and notifications.
2Abendsegler/GClh pull request #2454
Opened 2023-11-17 16:57 UTC by 2Abendsegler

#2410

2023-11-17 17:22 UTC, 2Abendsegler commented
@capoaira 
Ich schon wieder. 🙄

Falls du magst, kannst du hier mal drüber schauen. Ich werde es als Beta in die nächste Version packen. Bitte aber nicht approven.

- [Hier](https://github.com/2Abendsegler/GClh/issues/2410#issuecomment-1805023662) steht im Groben welche Features bisher eingebaut wurden.
- Man muss den Parameter [(Beta version) Improve notification list and notifications](https://www.geocaching.com/my/#GClhShowConfig#a#settings_improve_notifications_beta) aktivieren.
- Es sind Anpassungen im `init.js` hier im PR zu beachten.

2023-11-18 14:37 UTC, capoaira commented
Wow, ich finde, das sieht schon richtig gut aus 👍👍👍

Ich habe noch zwei Sachen gefunden, die ich schön finden würde und einen kleinen Bug.

1. Es wäre schön, wenn beim Ändern des Cachetypes, die Logtypen erhalten bleiben (sofern möglich). So kann man das Copyfeature effizienter nutzten
2. Es wäre schön, wenn man Notification mit demselben Namen gleichzeitig (de)aktivieren könnte. (z.B. mit Rechtsklick, so wie man auch bei den PQs mehrere gleichzeitig (de)aktivieren kann)

3. Wenn man eine Notification löscht, wird sie ausgegraut. Wenn sich endgültig gelöscht wird, ist jedoch immer noch zu sehen. Hier wäre es sinnvoll, entweder die Notification dann verschwinden zu lassen oder einen "rückgängig" Button (bzw. den "bearbeiten" Button) anzuzeigen, mit der man die Notification wieder herstellen könnte.

Soweit mein erster Eindruck, ich habe noch nicht strategisch alle Funktionen abgearbeitet, sondern nur meinen eigenen Workflow, beim Erstellen neuer getestet.

Ich finde die Erweiterungen klasse und werde sie bei meinem nächsten Urlaub auf jeden Fall nutzen 😊👍

2023-11-18 15:25 UTC, 2Abendsegler commented
Alles super Verbesserungsvorschläge! 
1. versuche ich noch einzubauen. 3. vielleicht auch. 2. Kommt wohl erst später.

2023-11-23 21:58 UTC, 2Abendsegler commented
@capoaira
Ich schon wieder. 🙄

> 1. Es wäre schön, wenn beim Ändern des Cachetypes, die Logtypen erhalten bleiben (sofern möglich). So kann man das Copyfeature effizienter nutzten
> 
> 2. Es wäre schön, wenn man Notification mit demselben Namen gleichzeitig (de)aktivieren könnte. (z.B. mit Rechtsklick, so wie man auch bei den PQs mehrere gleichzeitig (de)aktivieren kann)
> 
> 3. Wenn man eine Notification löscht, wird sie ausgegraut. Wenn sich endgültig gelöscht wird, ist jedoch immer noch zu sehen. Hier wäre es sinnvoll, entweder die Notification dann verschwinden zu lassen oder einen "rückgängig" Button (bzw. den "bearbeiten" Button) anzuzeigen, mit der man die Notification wieder herstellen könnte.

Punkt 1. habe ich eingebaut. Deine beiden anderen Punkte schaffen es nicht mehr in die nächste Version. Den Delete Process habe ich für die nächste Version komplett raus genommen.

Ich habe gut getestet. Vielleicht hast du aber trotzdem noch mal Zeit drüber zu schauen. Wie erwähnt, will ich spätestens am Samstag Abend eine neue Version bringen.

* [Hier](https://github.com/2Abendsegler/GClh/issues/2410#issuecomment-1805023662) steht im Groben welche Features bisher eingebaut wurden.
* Es sind Anpassungen im `init.js` hier im PR zu beachten.

2023-11-24 18:15 UTC, capoaira requested changes
Sieht wirklich alles Klasse aus. 👍

Mir ist nur noch eines aufgefallen: Bei mir wird die E-Mail nicht angezeigt:
![grafik](https://github.com/2Abendsegler/GClh/assets/50927164/9ad0b52f-cbab-4ff5-b108-774e32408085)

Ich gehe davon aus, dass es daran liegt, dass ich nur eine angegeben habe und daher kein `select` zur Verfügung steht.

2023-11-24 19:53 UTC, 2Abendsegler commented
@capoaira 
Super!
Passt auch bei mir.
Ich merge dann.

2023-11-24 19:54 UTC, merged