[Log Form] Collection
2Abendsegler/GClh pull request #2457
Opened 2023-11-21 00:29 UTC by 2Abendsegler

#2424

- Build JSON from page data `__NEXT_DATA__`.
- Build isEvent from JSON from page data `__NEXT_DATA__`.

Default logtypes:
- Note that the feature may disappear again and will have to be rebuilt.
- Decode cacher name.
- Use isEvent from page data.
- Check the selected logtype against the possible logtypes.
- Revision of the default log types in the config.

Signature: 
- Adopt almost all changes from PR of capoaira #2441.
- In drafts, add a line break between draft content and signature.
- Set focus on logtext in first position.

Log templates:
- Adjust the size of the logfield.

Show length of logtext and word count:
- Note that the feature may disappear again and will have to be rebuilt.

Show message in case of unsaved log:
- Note that the feature may disappear again and will have to be rebuilt.

Show additional cache info:
- Note: The fields difficulty, terrain, favoritePoints and premiumFavoriteScore are available in page data ("__NEXT_DATA__", props.pageProps.loggable), but the fields have no values. In addition, the watchers are not included there. Therefore, we cannot replace the website reading with this data.

Autovisit:
- Set action type by log type only if log type changed.

Replicate TB-Header to bottom:
- Note that the feature may disappear again and will have to be rebuilt.

Send Log with F2:
- Note that the feature may disappear again and will have to be rebuilt.
- Make note in the general area for F2 handling, where the development for the log form is.

Others:
- Moved a few parameters to the correct place in the config.
- Hiding the TBs during inline logging (settings_log_inline_tb) no longer made sense for a long time because it was no longer supported in the new log form. Parameters removed in the coding.

2023-11-23 21:29 UTC, 2Abendsegler commented
@capoaira 
Hey,

ich habe noch zahlreiche Änderungen am Log Formular gemacht. Aus meiner Sicht ist die Seite jetzt fertig. Ich habe gut getestet, vielleicht könntest du aber trotzdem noch drüber schauen. Ich würde gerne spätestens am Samstag Abend eine neue Version bringen. 

Signaturen und Log Templates können immer noch verschwinden, wenn man beispielsweise einen Logtype auswählt. Ich habe keine Lösung gefunden. Womöglich gibt es auch keine Lösung von unserer Seite, weil es scheinbar mit der Art der Verarbeitung der Webseite zusammenhängt. Das Logtext Feld wird meines Erachtens ohne Grund aktualisiert, wenn beispielsweise ein Logtype ausgewählt wird.

Ein Workaround ist klar. Man muss nach dem Einstellen der Signatur oder den Log Templates im Logtext eine Eingabe machen. Genau das ist nun auch bei den Signaturen und Log Templates beschrieben. Es gibt sie auch nur, wenn man die entsprechenden neuen Config Parameter aktiviert. Aktiviert man einen der Parameter, gibt es ein Popup mit einer Info. Ich hoffe die Info ist verständlich. Damit ist zumindest sichergestellt, dass jeder Nutzer der Features darüber informiert wird. Nutzer die das Changelog oder die Foren nicht verfolgen, werden die Features dann nicht haben. Die Parameter sind im ersten Beitrag im PR fett markiert.

Für den Fall das eine Signatur dann doch verschwindet, kann man sie über neue Parameter bei den Log Templates vorsehen und dann auch von dort aus integrieren. 

Ich hoffe wir können das so lassen. Ich habe nämlich ehrlich gesagt die Nase voll von dem ganzen Mist auf der Seite.

2023-11-24 17:30 UTC, capoaira approved these changes
Wow, hier hast du ja eine Menge gemacht. Klasse 👍

Ich habe auch nochmal alles getestet und keine Fehler gefunden.

2023-11-24 18:57 UTC, capoaira requested changes
Mir ist gerade aufgefallen, dass die Signatur bei Entwürfen mit Inhalt nicht eingefügt wird :(

2023-11-24 20:22 UTC, 2Abendsegler commented
@capoaira 
Sehr gut aufgepasst!
Jetzt sollte es passen. Schau bitte noch mal kurz.
Vielen Danke fürs Testen!

2023-11-25 08:29 UTC, 2Abendsegler commented
@capoaira 
Moin,
das musst du gar nicht mehr erneut prüfen.
Ich merge das selbst.
Danke noch mal für Testen.

2023-11-25 08:29 UTC, merged