keep signature
2Abendsegler/GClh pull request #2460
Opened 2023-11-25 17:29 UTC by capoaira

fixes #2455

@2Abendsegler So, das ist mein aktueller Stand, Templates funktionieren so weit.
Bei der Signatur gibt 2 Bugs:
1. Wenn `.lt-mirror__canvas` nicht existiert, verschwindet die Signatur
2. Wenn es existiert, wird die Signatur zwar erneut eingefügt, aber das Logdatum wird nicht übernommen.

Was noch auf meiner ToDo List steht:
- Für die Signatur teste ich nur auf ein leeres Feld, hier muss noch mit Drafts getestet werden.

Ich brauche jetzt aber erstmal eine kleine Pause.... Bin mir nicht sicher, ob ich heute noch fertig werde.

2023-11-25 18:22 UTC, 2Abendsegler commented
@capoaira 
Alles gut. 
Den Go Live habe ich für heute schon abgehakt. Ich will diese Anpassungen auch noch gut testen und das würde ich heute auch nicht mehr schaffen. Und falls alles funktioniert, muss ich auch noch ein paar Anpassungen machen.
Also, gönn dir eine Pause. 
Und gib Bescheid wenn du fertig bist. Wenn nicht heute dann halt später.

2023-11-25 19:58 UTC, capoaira commented
So, jetzt müsste es funktionieren.
Mit den beiden Variablen `gclhChanges` und `keepGClhChanges` wird überwacht, ob wir Änderungen gemacht haben. Die Variabel `signature` ist nötig, um im `logpageObserver` die Signatur neu zu laden, wenn das Feld `.lt-mirror__canvas` noch nicht geladen wurde.
Der `mirrorObserver` hat 3 Zustände:
1. Wir haben gerade Änderungen durch geführt
2. Es wird irgendein Feld angeklickt und der mirror löscht unseren Text => keepGClhChanges sorgt dafür, dass der Logtext wieder eingetragen wird.
3. Wir haben keine Änderungen und speichern uns den Logtext

2023-11-25 22:39 UTC, 2Abendsegler requested changes
Geniale Sache, super!

Vom Prinzip her scheint das zu klappen, auch wenn sich noch ein paar Probleme zeigen. 

1. Log ohne Draft. TypeError `$('#gc-md-editor_md')[0].value` weil `$('#gc-md-editor_md')[0]` noch nicht vorhanden.
Alt:
`if (signature && $('#gc-md-editor_md')[0].value == (pageData.logValues.note || '')) {`
Neu: Das sollte an der Funktionalität nichts ändern, oder?
`if (signature && $('#gc-md-editor_md')[0] && $('#gc-md-editor_md')[0].value == (pageData.logValues.note || '')) {`

2. Log ohne Draft. Die Meldung 'Hey wait ...' kommt bei mir nie zum Zug. 
Ich denke sie soll dazu dienen, wenn ich zuletzt noch ein Log Template ausgewählt habe, ohne eine weitere Eingabe gemacht zu haben. Bei mir kommt keine Meldung, es wird trotzdem gespeichert, ohne den Inhalt des Log Templates. 
Vielleicht könnten wir aus dem Hey noch ein Please machen.

3. Draft ohne Logtext aus dem Draft. Anstatt dessen kommt Signatur wie bei einem leeren Log. Das passiert nicht immer, nur gelegentlich.
Ich vermute dass der Logtext aus dem Draft einfach noch nicht vorhanden ist. Womöglich meint dein Coding festgestellt zu haben, dass die Signatur fehlt und gibt sie in den Logtext. Das Problem sollte durch dein neues Coding entstehen. Zumindest kann ich es ohne dein Coding nicht nachstellen.
![Draft 1](https://github.com/2Abendsegler/GClh/assets/22332216/804d9482-3570-4c7c-9b6d-7c47d155c4ff)

4. Draft mit Logtext aus dem Draft. Die Dropdown Listen beim Log Type und bei den Log Templates klappen nur kurz auf und sind dann wieder weg. Das passiert nicht immer, nur gelegentlich. 
Man sieht das kurze Erscheinen auf dem gif nur einmal kurz, obwohl ich mehrfach drauf geklickt habe. Besser bekomme ich es nicht hin. 
![Draft 2](https://github.com/2Abendsegler/GClh/assets/22332216/90038e0a-2649-4dde-84bd-c740021c7cfd)

5. Log ohne Draft, Signatur wird eingeblendet. Nun wähle ich ein Log Date oder einen Log Type und die Anzahl Wörter werden angezeigt. Die Anzahl Zeichen aber nicht. 
Wenn wir das eine ermitteln können, dann vermutlich auch das andere.

2023-11-26 10:21 UTC, capoaira commented
Hm, das ist alles sehr komisch:
1. Tritt bei mir nicht auf, habe es aber angepasst
2. Gestern hat es bei mir funktioniert, heute komme ich mit dem Coding in eine Endlosschleife aufpoppender Nachrichten, die ich nur durch Schließen des Fensters beenden kann. (Das mit dem Please habe ich angepasst)
3. Kann ich nicht reproduzieren
4. Kann ich nicht reproduzieren
5. Der Zeichencounter ist von GS, der Word Counter ist von uns, daher wird der Zeichencounter erst aktualisiert, wenn auch die Logvorschau aktualisiert wird. Das sollte auch im alten Coding der Fall sein. Kann ich natürlich trotzdem anpassen, indem wir das selber im `change` Event anpassen

2023-11-26 11:17 UTC, 2Abendsegler commented
1., 3. und 4. treten bei mir auf, weil es immer wieder `Uncaught Error: Minified React error #418` gibt. Ich bin froh, dass es den Fehler immer wieder bei mir gibt. Nur deshalb habe ich die ganzen Schleifen ... eingebaut und konnte sie auch testen. 

zu 2. `function buildWarningForGClhChanges`
> 2\. Gestern hat es bei mir funktioniert, heute komme ich mit dem Coding in eine Endlosschleife aufpoppender Nachrichten, die ich nur durch Schließen des Fensters beenden kann. (Das mit dem Please habe ich angepasst)

Ändere bitte mal folgendes ab, dadurch kommen nur noch eine bzw. zwei Meldungen:
Alt:
`if ($('.post-button-container .submit-button:not(.gclh_change_warning)')) {`
Neu:
`if ($('.post-button-container .submit-button:not(.gclh_change_warning)')[0]) {`

Bei der Auswahl eines LogTypes wird .gclh_change_warning entfernt und das bind erfolgt ein zweites Mal. Vor dem bind `$('.post-button-container .submit-button').bind('click', (e) => {`, sollte deshalb ein unbind stattfinden. 

Bei mir wird der Schalter `keepGClhChanges` nie gesetzt. Das `$('.lt-mirror__canvas')[0]` kann ich aber auch nicht finden. Wann kommt das und wo steht das.

---
off topic: Bei mir ist gerade ein Stromausfall im ganzen Haus. Wo gibt es denn noch so was. Ich arbeite gerade über einen mobilen Hotspot.

2023-11-26 11:17 UTC, 2Abendsegler commented
zu 5. Vergiss das. :)

2023-11-26 11:34 UTC, capoaira commented
> 1., 3. und 4. treten bei mir auf, weil es immer wieder `Uncaught Error: Minified React error #418` gibt. Ich bin froh, dass es den Fehler immer wieder bei mir gibt. Nur deshalb habe ich die ganzen Schleifen ... eingebaut und konnte sie auch testen.

Hm, dann musst du das wohl versuchen... Ich hasse es, wenn Fehler nicht bei jeden reproduzierbar sind, zumal wir denselben Browser nutzen :(

> Ändere bitte mal folgendes ab, dadurch kommen nur noch eine bzw. zwei Meldungen: Alt: `if ($('.post-button-container .submit-button:not(.gclh_change_warning)')) {` Neu: `if ($('.post-button-container .submit-button:not(.gclh_change_warning)')[0]) {`
> 
> Bei der Auswahl eines LogTypes wird .gclh_change_warning entfernt und das bind erfolgt ein zweites Mal. Vor dem bind `$('.post-button-container .submit-button').bind('click', (e) => {`, sollte deshalb ein unbind stattfinden.

Oh man, manchmal sieht man den Wald vor lauter Bäumen nicht 😅. Danke, jetzt klappt es. Ich nutze jetzt nur `.post-button-container`, wie wir das auch schon bei der unsavedChanges Warnung machen.

> Bei mir wird der Schalter `keepGClhChanges` nie gesetzt. Das `$('.lt-mirror__canvas')[0]` kann ich aber auch nicht finden. Wann kommt das und wo steht das.

Der ist bei mir mal von Anfang an da, und mal erst ab dem ich meinen Curser in das Textfeld setzte.

---
> off topic: Bei mir ist gerade ein Stromausfall im ganzen Haus. Wo gibt es denn noch so was. Ich arbeite gerade über einen mobilen Hotspot.

Oh, das hatte ich zum Glück lange nicht mehr... Kein Licht, kein Desktop PC, kein WLAN, ich wüsste nichts mir anzufangen 😅.

2023-11-26 11:52 UTC, 2Abendsegler commented
> > Das `$('.lt-mirror__canvas')[0]` kann ich aber auch nicht finden. Wann kommt das und wo steht das.
> 
> Der ist bei mir mal von Anfang an da, und mal erst ab dem ich meinen Curser in das Textfeld setzte.

Kannst du bitte mal einen Screenshot aus dem Inspektor einstellen, wo ich das sehen kann?

2023-11-26 11:57 UTC, capoaira commented
> > > Das `$('.lt-mirror__canvas')[0]` kann ich aber auch nicht finden. Wann kommt das und wo steht das.
> > 
> > 
> > Der ist bei mir mal von Anfang an da, und mal erst ab dem ich meinen Curser in das Textfeld setzte.
> 
> Kannst du bitte mal einen Screenshot aus dem Inspektor einstellen, wo ich das sehen kann?

Der ist bei mir direkt über der textarea.

Ich habe gerade gemerkt, dass das von einem Add-On ist, das ich nutzte und nicht von GS 😢
Mal sehen, ob ich das Coding auf irgendein Element von GS umstellen kann.

Sorry...

2023-11-26 12:09 UTC, 2Abendsegler commented
@capoaira 
Ich habe einen Vorschlag.
Lass uns mit der aktuellen collector Version und mit den Einschränkungen beim Logtext live gehen. Ich werde im den Foren noch mal explizit auf die Problematik hinweisen und auch schreiben, dass wir noch dran sind eine Lösung zu suchen.

Ich gehe etwas auf dem Zahnfleisch. Ich habe die letzten Wochen jede freie Minute hier rein gesteckt und habe etliche Sachen schleifen lassen. Ich kann aktuell nicht noch weitere Zeit, womöglich Tage investieren, bis das hier rund läuft.

Du kannst noch weiter nach einem Ersatz für den mirror suchen und das Coding entsprechend anpassen. 
Nach dem Go Live haben wir wieder etwas Luft, schließlich gibt es einen Workaround.

Was meinst du?

2023-11-26 12:18 UTC, capoaira commented
Warte doch nochmal ein paar Minuten damit ...

2023-11-26 12:27 UTC, capoaira commented
So, ich habe einmal alles schnell durchgetestet und bei mir funktioniert es so weit.
Wenn es bei dir jetzt nicht sofort funktioniert, hau einfach die neue Version ohne das hier raus.

Ich kann verstehen, dass du nicht mehr so viel Zeit hier reininvestieren kannst. Du hast hier wirklich viel in kurzer Zeit geschafft. Ich hatte leider nur Zeit zum testen :(

2023-11-26 13:50 UTC, merged