[Dashboard] Hide TB-Logs from activity feed
2Abendsegler/GClh pull request #2521
Opened 2023-12-12 15:33 UTC by capoaira

closes #2520

2023-12-13 06:08 UTC, 2Abendsegler requested changes
Moin,
ich habe noch 2 Dinge im Coding markiert.

2023-12-13 06:08 UTC, 2Abendsegler commented on gc_little_helper_II.user.js
> +                    container.parentNode.parentNode.style.display = 'none';
Damit wird auch die Dropdown Liste "Community, Yours ..." entfernt, wenn es sich um das erste Datum handelt.
![grafik](https://github.com/2Abendsegler/GClh/assets/22332216/53e634d1-5210-4af5-9719-d2872eb91cdb)

2023-12-13 06:08 UTC, 2Abendsegler commented on gc_little_helper_II.user.js
> +                    $('.activity-block-header')[0].style.display = 'none';
Das hier kann ich nicht nachvollziehen. Das bekomme ich so nicht hin. Das scheint mir aber auch unproblematisch. Wenn es also bei dir Sinn macht, ok.

2023-12-13 06:21 UTC, 2Abendsegler commented on gc_little_helper_II.user.js
> +                    $('.activity-block-header')[0].style.display = 'none';
Ach, jetzt verstehe ich es. Hier geht es ja genau um den Fall wie oben beschrieben, wenn es sich um das erste Datum handelt. Das hier ist also letztlich für das Ausblenden der Dropdown Liste verantwortlich.
Das ist wieder total blöd realisiert.

2023-12-14 15:39 UTC, capoaira commented on gc_little_helper_II.user.js
> +                    container.parentNode.parentNode.style.display = 'none';
Gut aufgepasst

2023-12-14 16:20 UTC, 2Abendsegler requested changes
Moin, sorry passt leider noch nicht.

Ohne hide:
![Unbenannt1](https://github.com/2Abendsegler/GClh/assets/22332216/a394f91a-60f7-430c-95a5-0f4b40abdfc8)

Mit hide
![Unbenannt2](https://github.com/2Abendsegler/GClh/assets/22332216/31bf43a0-a28a-4733-8e9d-4487cf9f8552)

2023-12-14 18:26 UTC, capoaira commented
Hm, das scheint wohl daran zu liegen, dass mehr als ein Tag ausgeblendet wird. Ist blöderweise ein Fall, den ich gerade nicht nachstellen kann... Ich guck mal, ob dennoch eine Lösung finde

2023-12-14 18:32 UTC, 2Abendsegler commented
Könntest du nicht noch ein TB Log für den 13.12. erfassen und dann nicht über Community sondern über Yours gehen. Das müsste dann doch das Gleiche sein?

2023-12-14 18:33 UTC, capoaira commented
Stimmt, das sollte gehen. Danke ;)

2023-12-14 18:53 UTC, capoaira commented
So, jetzt sollte es passen ;)

2023-12-14 21:37 UTC, 2Abendsegler approved these changes
Großartig!

2023-12-14 21:37 UTC, merged