feat(Cache Listing): character count for Personal Cache Note
2Abendsegler/GClh pull request #2563
Opened 2024-02-28 12:22 UTC by capoaira

fix #2560
also refactors the CreateCounterElement function, to use it globally

2024-03-13 10:11 UTC, 2Abendsegler requested changes
Tut mir leid, dass ich erst jetzt dazu komme hier rein zu schauen! 

Sieht so weit gut aus bis auf zwei kleine Fehler. Die treten nur in der Personal Cache Note auf, nicht im Log. 

- Wenn man nach Anwahl des Cache Listings erstmalig zum Edit in die Personal Cache Note geht, steht der Zähler zuerst mal auf 0 auch wenn bereits Text vorhanden ist. (Bei einem Browser Refresh der Seite funktioniert es richtig. Rufe ich die Seite allerdings in einem neuen Tab auf, funktioniert es wiederum nicht.)
- Ein Zeilenvorschub wird als 2 Zeichen gewertet. Richtig scheinen aber nur 1 Zeichen. Test: Ich habe 2499 Zeichen eingegeben und dann irgendwo mittendrin einen Zeilenvorschub eingegeben. Der Zähler zeigt dann 2501 Zeichen. Ich kann speichern. Gehe ich wieder rein, steht der Zähler wieder auf 2501 Zeichen. (Emojis zählen als zwei Zeichen, das ist richtig.)

2024-03-13 10:17 UTC, capoaira commented
> Tut mir leid, dass ich erst jetzt dazu komme hier rein zu schauen!

Alles gut, kein Problem

Ich schaue mir beides an, allerdings fliege ich Samstag nach Bangkok und komme erst in der ersten Aprilwoche wieder. Ich gehe davon aus, dass ich erst danach dazu kommen werde.

2024-03-13 10:20 UTC, 2Abendsegler commented
Bangkok ... hört sich gut an. Viel Spaß. 😊

2024-03-13 10:28 UTC, capoaira commented
> Bangkok ... hört sich gut an. Viel Spaß. 😊

Danke 😊.

2024-08-10 10:52 UTC, capoaira commented
Moin, weißt du, ob es noch eine Möglichkeit gibt, die alte Logseite zu nutzen?

2024-08-10 11:03 UTC, 2Abendsegler commented
> Moin, weißt du, ob es noch eine Möglichkeit gibt, die alte Logseite zu nutzen?

Moin,
wenn der Parameter [Use old-fashioned log form to log a draft](https://www.geocaching.com/my/#GClhShowConfig#a#settings_drafts_old_log_form) gesetzt ist, gelangt man von den Drafts immer noch ins alte Log Formular. Ohne Draft geht das meines Wissens nicht mehr.

2024-08-10 11:05 UTC, capoaira commented
Alles klar. Danke. Dann werde ich an dem Log counter nicht herum fuschen 😅

2024-08-10 12:05 UTC, 2Abendsegler requested changes
Noch eine Kleinigkeit, nur falls das nicht mehr viel Aufwand macht.
Wenn man nach Anwahl des Cache Listings erstmalig zum Edit in die Personal Cache Note geht, ist der Zähler nicht rot wenn bereits 2500 Zeichen vorhanden sind.

2024-08-10 16:30 UTC, 2Abendsegler approved these changes
Cool!

2024-08-10 16:30 UTC, merged