Changed width of log-view and editor to width of browser-window.
2Abendsegler/GClh pull request #2564
Opened 2024-03-02 13:35 UTC by ColleIsarco

The width of the log-view and log-editor is set to 90 percent of the browser window

2024-03-02 15:47 UTC, capoaira requested changes
Hello and thank you for your contribution.

The feature works well.

But I don't want to use it, since I have an ultra-wide monitor. Please add a config param So that the feature can be turned on and off (default off)

@2Abendsegler We have the setting "Page width" `settings_new_width`. I never used it, so I'm not sure if that should be used instead?

2024-03-02 16:24 UTC, 2Abendsegler commented
Yes, where we change the width of elements on the screen, we derive the width from this parameter `settings_new_width`. This should be done here in the same way. And it should be implemented via css so that we don't have to wait for the elements in the log form. The right place for the coding is then the `function newWidth`, probably in the area `// Besonderheiten:`.

Yes, we should also provide a parameter to enable the feature. By default it could be enabled.

2024-03-03 23:45 UTC, 2Abendsegler commented
What I just noticed: 
The log view page is already using the maximum width. In my opinion, no changes should be necessary here. If there is empty space on the right side or the width of the screen is not being used, then this is probably due to the fact that an ad blocker does not completely remove the advertising on the right side of the page.

2024-03-05 07:24 UTC, ColleIsarco commented
> Yes, where we change the width of elements on the screen, we derive the width from this parameter `settings_new_width`. This should be done here in the same way. And it should be implemented via css so that we don't have to wait for the elements in the log form. The right place for the coding is then the `function newWidth`, probably in the area `// Besonderheiten:`.
I know nothing about css but it looks like in newWidth the width is set to an absolut value, isn't. And then it will not dynamically adjust to the current width of the main window. I think that is the reason why it is not a good idea to change thw browser windows size.  See screenshot below:
![Screenshot from 2024-03-05 08-21-07](https://github.com/2Abendsegler/GClh/assets/12955602/e46f6775-2310-4ef3-8677-25bcc4bd92b5)
What do you think?

> Yes, we should also provide a parameter to enable the feature. By default it could be enabled.
I'm fine with having an option for changing the width inside the browser.

2024-03-05 07:27 UTC, ColleIsarco commented
> What I just noticed: The log view page is already using the maximum width. In my opinion, no changes should be necessary here. If there is empty space on the right side or the width of the screen is not being used, then this is probably due to the fact that an ad blocker does not completely remove the advertising on the right side of the page.

No, there is actually no ad on the page at all. The empty space is distributed evenly on both sides, like the screenshot taken in a bare browser shows:
![Screenshot from 2024-03-05 08-25-54](https://github.com/2Abendsegler/GClh/assets/12955602/24d2c93d-c9b4-45ba-b8d8-162482746f11)

2024-03-05 11:55 UTC, 2Abendsegler commented
Das Cache Listing ist ein gutes Beispiel. Die Breite einzelner Bereiche ist fest vorgegeben und auf eine Bildschirmbreite von 900 oder 950 Pixel ausgelegt. Mit dem Parameter [Page width](https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width)  `settings_new_width` passen wir nun die einzelnen Bereiche an eine größere Bildschirmbreite an. Du musst also nur "Page width" korrekt einstellen, dann passt es auch. Unsere Einstellung passt sich nicht an variable Bildschirmgrößen an, das scheint mir aber auch nicht notwendig, weil man in der Regel mit der gleichen Bildschirmgröße arbeitet.

Wenn du den Parameter "Page width" einstellst, dann sollte das bereits für die Log Anzeige funktionieren, versuch es bitte mal. 

Falls dann rechts mehr Leerraum ist als Links, so wie es auch im Moment etwas den Anschein hat, dann könnte das mit deinem Ad Blocker uBlock Origin zusammen hängen. Gegebenenfalls könntest du die Geocaching Seiten von deinem Ad Blocker ausnehmen und anstatt dessen den [GC Ad Blocker](https://github.com/2Abendsegler/GC_ad_blocker ) verwenden, der das speziell für die Geocaching Seiten womöglich besser hinbekommt.

Wir können das Feature auch per CSS in `function newWidth` einbauen. Es ist aber auch nicht so schwer, das Wichtigste kann man aus der bestehenden Function erkennen. Dabei werden deine Styles width und maxWidth nur anders aufbereitet angegeben. Aber, wie schon geschrieben, wir können das auch übernehmen.

2024-03-13 10:17 UTC, 2Abendsegler commented
@ColleIsarco
Hast du mal auf der Log View Seite mit dem Parameter [Page width](https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width) `settings_new_width` getestet? 
Sollen wir das Feature für die Log Form und Log Edit Seite per CSS in `function newWidth` einbauen? Das ist schnell gemacht und du könntest danach mal testen.

2024-04-12 15:34 UTC, 2Abendsegler commented
Es gibt den neuen Pull Request #2580, in dem unter anderem dieses Thema (#2565) enthalten ist.
Ich schließe diesen Pull Request.

2024-04-12 15:34 UTC, closed without merging